#define SIMPLE_RUMOUR_NUM	95
#define CITIZEN_RUMOUR_NUM	10

string DEFAULT_TEXT[19] = {
"Man sagt, ein- bis zweimal im Jahr verlässt aus Porto Bello die sogenannte Goldflotte den Hafen – ein Konvoi aus Dutzenden Handelsschiffen, eskortiert von Kriegsschiffen. Die Route ist immer dieselbe, streng festgelegt: Von der spanischen Hafenstadt Porto Bello geht es nach Norden Richtung Havanna, und von dort über den Atlantik nach Europa. Es versteht sich von selbst, dass an Bord der Schiffe der Goldflotte unermessliche Schätze transportiert werden.",
"Wusstest du, dass du beim Angriff einer feindlichen Flotte auf eine Kolonie beim Erobern helfen kannst? Fahr einfach zum Flaggschiff der Angreifer, schick ein Beiboot rüber und verhandle mit dem Admiral über die Bedingungen.",
"Es stellt sich heraus, dass du bei einem Angriff auf eine Kolonie tatsächlich bei der Verteidigung helfen kannst. Schleiche dich einfach durch den Dschungel in die Stadt und sprich mit dem Gouverneur über die Bedingungen, unter denen du die Kolonie gegen die Angreifer unterstützen kannst.",
"Manchmal bekommst du wichtige Informationen in der Taverne – entweder von den Gästen oder vom Personal. Schließlich ist das der erste Ort, den jeder Fremde ansteuert.",
"Um in eine feindliche Stadt zu gelangen, kannst du in einer nahegelegenen Bucht an Land gehen und dich durch den Dschungel zu den Stadttoren schleichen. Am besten tust du das allerdings bei Nacht.",
"Käpt’n, wenn du einen feindlichen Kapitän gefangen nimmst, solltest du ihn nicht gleich über die Klinge springen lassen! Für einen reichen Gefangenen kannst du nämlich oft ein ordentliches Lösegeld kassieren. Oder du setzt ihn einfach an irgendeinem verlassenen Strand aus.",
"Hier ist es heiß und feucht, aber von April bis Oktober tobt die Regenzeit mit tropischen Schauern und heftigen Stürmen. Ich wünsche wirklich niemandem, auf offener See in so einen Sturm zu geraten!",
"Um erfolgreich zu handeln, brauchst du profitable Routen, ein gutes Gespür fürs Geschäft und manchmal auch freundschaftliche Beziehungen zu Ladenbesitzern. Ein fähiger Quartiermeister ist außerdem Gold wert beim Handel.",
"Käpt’n, denk dran: Im Seegefecht ist die Breitseite am gefährlichsten. Versuch also, den Feind immer mit deinen Seitenkanonen zu treffen – aber pass auf, dass du selbst nicht in die Schusslinie seiner Breitseite gerätst.",
"Manchmal ist es klüger, einer Seeschlacht mit überlegenen Gegnern aus dem Weg zu gehen – aber dafür musst du richtig schnell sein. Wenn es keinen anderen Ausweg gibt und du fliehen musst, wirf am besten etwas Ladung über Bord. So wird dein Schiff leichter und du kannst mehr Fahrt aufnehmen, um deinen Verfolgern zu entkommen.",
"Wer sich der Piraterie verschrieben hat, kann in der Taverne wertvolle Informationen über reiche Händler aufschnappen. Doch nicht jeder Stammgast teilt sein Wissen über leichte Beute. Nur wer selbst eine dunkle Vergangenheit hat, darf auf solche Tipps hoffen. Wobei – wie man sagt, öffnet Gold bekanntlich jede Tür.",
"Um die Gunst des Generalgouverneurs zu gewinnen – und gleich dazu einen Kaperbrief einer der Nationen zu erhalten – musst du erst einem Gouverneur einer ihrer Kolonien treu und zuverlässig dienen. Es gab aber auch schon Fälle, in denen berüchtigte Piraten einfach einen Kaperbrief von zwielichtigen Beamten gekauft haben.",
"Auf den Kopf eines dreisten Piraten oder berüchtigten Banditen setzen die Kolonialbehörden oft ein hohes Kopfgeld aus. Dann machen sich Abenteurer aus der ganzen Neuen Welt auf die Jagd – sie verfolgen ihn zu Land und zu Wasser.",
"Das Leben der Piraten ist ziemlich gefährlich, deshalb versteckten sie ihre Beute oft an geheimen Orten und zeichneten sorgfältig Schatzkarten. Heute sind solche Karten auf den Inseln weit verbreitet, und man kann sie bei allerlei zwielichtigen Gestalten kaufen.",
"Um ein Schiff richtig zu führen, brauchst du eine erfahrene Crew. Eine gute Mannschaft ist Gold wert, also schone deine Leute in hitzigen Gefechten. Ein fähiger Schiffsarzt kann Verluste gering halten – und ein Vorrat an Medizin an Bord schadet nie.",
"Auf mittelgroßen und großen Schiffen gibt es neben der Kapitänskajüte auch den Offiziersraum – der perfekte Ort, um allen deinen Offizieren die nötigen Anweisungen zu geben.",
"Die Bukaniere waren schon immer für ihre Jagdkünste und ihre Treffsicherheit berühmt. Ihr Geheimnis? Sie halten ihre Waffen stets in bestem Zustand. Also vergiss nicht, genug Kugeln für deine Pistole zu kaufen – und sorge dafür, dass du eine gute Pistole bei dir hast.",
"Denkt daran: Jede eurer Taten wirkt sich auf euren Ruf aus. Gerüchte verbreiten sich schnell, und auch über euch wird so einiges erzählt. Ein schlechter Ruf kann euch beim Handeln schaden, aber beim Entern kann er euch helfen, den Feind einzuschüchtern. Vielleicht ergibt er sich dann sogar kampflos.",
"Achtet immer auf die Moral eurer Mannschaft. Wenn sie aufmüpfig ist, steht ihr kurz vor einer Meuterei. Da helfen manchmal ein paar Münzen – oder ein Fass Rum. Wie man so sagt: Lieber ein schlechter Kurs als eine Meuterei an Bord.",
};
/// Если новостей нет .
string NO_RUMOUR_TEXT[SIMPLE_RUMOUR_NUM] = {
"In letzter Zeit gibt es nichts Spannendes zu berichten. Das Leben verläuft ruhig und friedlich. Kaum zu glauben!",
"Hier ist alles ruhig und friedlich. Schiffe kommen nur selten vorbei, also ist in letzter Zeit nichts Besonderes passiert.",
"Die Ankunft eures Schiffs ist gerade in aller Munde!",
"Ich kann mich an nichts Besonderes erinnern. Nicht mal eine ordentliche Schlägerei in der Taverne gibt’s hier oft.",
"Ich fürchte, ich habe keine Neuigkeiten für dich – schon lange nichts Interessantes mehr gehört...",
"Ach, was für Zeiten... Unser Gouverneur hat schon wieder die Steuern erhöht. Mein Nachbar und ein paar Kumpel von ihm sind deshalb in den Dschungel geflohen, als man ihnen wegen Steuerschulden mit dem Kerker drohte.",
"Was sollen die Leute denn machen? Entweder gehen sie auf eigene Faust auf Beutezug oder heuern bei waghalsigen Kapitänen an – alles ist besser, als im Gefängnis den Fraß zu löffeln.",
"Man sagt, die Soldaten in der Garnison haben seit fast einem Jahr keinen Sold mehr aus Europa bekommen. Jetzt geht das Gerücht um, dass vor Kurzem ein paar von ihnen aus der Festung desertiert sind. Und wohin sollen sie schon gehen? Ist doch klar – sie werden zu Straßenräubern... Was uns nicht gegeben wird, holen wir uns eben selbst, denken die wohl. Ehrliche Leute trauen sich kaum noch vor die Stadttore.",
"Man sagt, unser Gouverneur hat sich mal wieder Möbel aus der Alten Welt für sein Anwesen bestellt. Und dabei laufen die Hälfte der Soldaten im Fort fast in Lumpen herum und zählen die Erbsen in ihrer Suppe einzeln ab.",

"Ich hab gehört, ein Offizier aus der Garnison hat seinen Familienschmuck verkauft, sich einen Lugger gekauft und ist vor ein paar Tagen zur See gefahren. Natürlich wurde er sofort zum Deserteur erklärt! Aber was sollte er denn tun, wenn die Vorgesetzten nur an ihren eigenen Vorteil denken?",
"Man munkelt, in Europa braut sich ein neuer Krieg zusammen. Das heißt wohl, die Steuern und Zölle steigen wieder – schlecht fürs ehrliche Geschäft. Die einfachen Leute werden sich dann lieber auf die Landstraßen schlagen, um den Steuereintreibern und Beamten zu entkommen.",

"Und wer sich aufs Meer wagt, sucht sein Glück bei Lady Fortuna – und läuft vor der Einbeinigen davon... Krieg bringt immer Armut und Räuberei mit sich, das geht Hand in Hand.",
"Schon gehört? Aus Europa ist eine neue Flotte angekommen – angeblich, um die Patrouillen zu verstärken und gegen Freibeuter vorzugehen. Aber ehrlich gesagt, von Piraten unterscheiden sich diese Patrouillen meist nur durch die Flagge am Großmast.",

"Kaum versiehst du dich, halten sie dich auf hoher See an, beschlagnahmen deine Ladung und denken sich irgendeinen Grund aus. Versuch dann mal zu beweisen, dass nicht dein Ochse das Haferfeld zertrampelt hat... Kein Wunder also, dass die Händler jetzt Konvois und Söldner anheuern müssen, um ihre Geschäfte zu schützen. Und was haben wir davon? Genau – der Rum wird schon wieder teurer! Zum Teufel mit dem ganzen Kram!",
"Man hört, dass es in Europa wieder unruhig ist... Das heißt, bald strömen hierher wieder allerlei Flüchtlinge und Glücksritter. Aber wer braucht die schon hier? Für solche gibt’s nur zwei Wege: auf der Landstraße plündern oder als Pirat zur See gehen.",

"Hehe, und die Gouverneure werden bestimmt wieder die Abgaben für die Garnisonen erhöhen. Ob Räuber im Dschungel oder Beamte in ihren feinen Büros – für das einfache Volk sind das alles die gleichen Blutsauger...",
"Habt ihr schon von den Fischerbooten gehört, die manchmal bei den Turks auftauchen? Ich sag euch, da haben Fischer nichts verloren! In diesen Gewässern gab’s noch nie einen einzigen Fisch!",

"Bei meinem alten, leckenden Kahn – ich schwöre, ich trink nie wieder Rum, wenn da alles mit rechten Dingen zugeht! Da stimmt doch was nicht!",
"Bei uns im Städtchen ist es meistens ruhig. Aber neulich gab’s hier beim Leuchtturm eine richtige Schlacht! Ein Kapitän hat mit ein paar einheimischen Händlern Schmuggelware verschoben – doch die Patrouille hat sie auf frischer Tat ertappt!",

"Leicht verdientes Geld bringt eben kein Glück, merkt euch das! Die Patrouillenbrigs haben die Schaluppe des Kapitäns am Ufer eingekesselt und geentert. Den Kapitän hat eine Kanonenkugel direkt erwischt – tot. Die einheimischen Hehler hat man im Fort gehängt. Und die armen Matrosen? Die wurden an die Faktorei verkauft. Ach ja... Möge Gott ihren armen Seelen gnädig sein...",//13
"Man erzählt sich, dass neulich ein englischer Militärkapitän einem holländischen Händler gegen Piraten geholfen hat. Kaum zu glauben! Allerdings hat er danach vom Kaufmann eine Belohnung gefordert.",
"Man erzählt sich, dass ein französischer Militärkapitän einem einsamen spanischen Händler gegen Piraten beigestanden hat. Als der Händler ihm eine Belohnung anbot, lehnte er sie ab. Es gibt also doch noch ehrenhafte Menschen in unserer Zeit!",
"Haben Sie schon die Neuigkeiten gehört, Captain? Man sagt, drei Freibeuter hätten sich kürzlich zusammengetan und einen Konvoi spanischer Handelsschiffe überfallen!",
"Man sagt, unser Gouverneur habe kürzlich einem Kapitän eine ordentliche Summe gezahlt, weil er ein Piratenschiff aufgespürt und gekapert hat, das den Händlern so viele Probleme bereitet hatte.",
"Man sagt, unser Gouverneur habe neulich eine ethnografische Expedition aufs Festland geschickt. Aber ehrlich gesagt, sieht das eher nach einem weiteren Piratenüberfall aus – auf den Galeonen waren jede Menge schwer bewaffnete Männer. Für bloßen Schutz sind das eindeutig zu viele Söldner, wenn du mich fragst.",
"Man sagt, unser Wirt hatte endlich mal Glück und hat beim Kartenspiel eine ordentliche Summe gewonnen. Bisher hat er nämlich immer nur verloren.",
"Man munkelt, unser Gouverneur hat wieder eine ordentliche Summe beim Würfeln verloren. Da können wir uns wohl schon mal auf höhere Steuern einstellen – am Ende müssen wir einfachen Leute wieder den Gürtel enger schnallen.",//20
"Neulich ging das Gerücht um, dass unser Gouverneur mächtig sauer auf einen Kapitän ist, mit dem er früher noch dicke war. Grund dafür ist, dass der Kapitän ihn beim Anteil der Beute übers Ohr gehauen hat.",
"Man sagt hier, einer der Assistenten unseres Gouverneurs wurde schon wieder mit Schmugglern gesehen. Die haben wohl wieder ihre dunklen Geschäfte besprochen.",
"Man munkelt, dass kürzlich ein Freibeuter zwei Piratenkapitäne gefangen genommen hat. Allerdings soll einer von ihnen an seinen Verletzungen aus dem Kampf gestorben sein. Es gibt jedoch Gerüchte, dass dieser angeblich tote Pirat sich mit Hinweisen auf einen Schatz freigekauft hat. So läuft das hier...",
"In letzter Zeit treibt ein Dieb in der Stadt sein Unwesen – er hat schon mehrere Häuser ausgeraubt, aber weder die Kommandantur noch das Militär konnten ihn fassen. Die Leute sind nervös geworden, und letzten Sonntag wäre dem Gouverneur deswegen fast die Residenz zertrümmert worden! Sogar Soldaten aus dem Fort wurden zur Verstärkung des Stadtgarnisons geholt, und die haben den aufgebrachten Mob auseinandergetrieben. Dabei wurde wohl auch jemand festgenommen...",
"In unserer Stadt treibt ein Dieb sein Unwesen. Er räumt die Häuser aus, sobald die Besitzer unterwegs sind, und die Garnison kann ihm nichts anhaben. Dieser Kerl ist wie ein Geist – niemand kann ihn fassen...",
"Man sagt, unser Hafenmeister kann für jedes Schiff die passenden Papiere ausstellen. Aber so einen Gefallen tut er nicht für jeden – da braucht’s schon den richtigen Draht und am besten eine persönliche Bekanntschaft…",
"Man munkelt, unsere Flotte bereitet eine Strafexpedition gegen die Piraten vor, die in letzter Zeit völlig außer Kontrolle geraten sind. Aber in dieser Expedition sollen nur Kaperfahrer mitmachen – und ihr wisst ja, was das für Leute sind. Im Grunde auch nur Piraten... Krähen hacken einander eben kein Auge aus, so sehe ich das.",
"Man munkelt, dass ein holländischer Kaper ein doppeltes Spiel treibt. Er überfällt Freund und Feind gleichermaßen. Wenn man ihn nur auf frischer Tat ertappen und aufhängen könnte – das wäre eine Warnung für alle anderen!",
"Man munkelt, dass vor Kurzem eine Strafexpedition von einem Beutezug zurückgekehrt ist – sie hatten gleich einen ganzen Konvoi gekaperter Schiffe im Schlepptau! Und angeblich waren die Laderäume so vollgestopft, dass man die Wasserlinie kaum noch sehen konnte.",
"Man sagt, Colonel Fox hat mal wieder einen Piraten geschnappt und ihn zum Trocknen an den Pier von Saint John’s gehängt. Mit dem Anführer der „Seefüchse“ ist wirklich nicht zu spaßen…",//30
"Man munkelt, dass kürzlich einer der Piratenanführer heimlich unseren Gouverneur besucht hat. Das Kuriose ist, seitdem lassen sich die Piraten nicht mehr in unseren Gewässern blicken, obwohl sie früher ständig hier unterwegs waren.",
"Man sagt, unser Geldverleiher steckt mit den Piraten unter einer Decke. In dieser Woche wurden schon zum dritten Mal Handelsschiffe überfallen – und genau diesen Händlern hatte der Geldverleiher gerade erst Kredite gegeben.",
"Man munkelt, dass in einer der Buchten hier in der Nähe Piraten dabei gesehen wurden, wie sie Kisten vom Schiff ins Beiboot verladen haben. Was die da wohl drin hatten?",
"Schon gehört? Neulich hat ein Piratengeschwader einen einzelnen Korvette unserer Marine angegriffen. Zum Glück gab es auf unserer Seite kaum Verluste, und die Halunken haben eine ordentliche Lektion bekommen.",
"Man erzählt sich, dass zwei Piratentartanen einen Kurier-Lugger überfallen haben. Der Lugger konnte sich verteidigen – seine einzigen Verluste waren zwei Fässer Rum.",
"Man erzählt sich hier, dass während eines Sturms vor der Küste der Nachbarinsel eine Piratenbrigantine gesunken ist – keiner der Piraten soll überlebt haben. So sieht’s aus...",
"Man munkelt, dass in unseren Gewässern das Schiff des Piraten namens James Hook gesichtet wurde. Sogar unsere Soldaten trauen sich seitdem kaum noch vor die Stadttore, und die Marinepatrouillen fahren nur noch in Dreiergruppen raus.",
"Man munkelt, dass kürzlich in einer der Buchten der Insel ein Handelsschiff gefunden wurde. Die ganze Besatzung war tot, und Ladung, Schiffskasse sowie Papiere waren verschwunden. Wieder ein Opfer des berüchtigten Piraten, der als Schwarzer Jack bekannt ist... Dieser Halunke hat sich sogar ein eigenes Markenzeichen ausgedacht: Er hat dem Kapitän die Buchstaben „B.J.“ in die Haut gebrannt und den armen Kerl am Rahende aufgeknüpft. Was für ein Scheusal!",
"Man munkelt, dass der Pirat mit dem Spitznamen „Der Lahme Hund“ kürzlich wieder ein Handelsschiff voller Gewürze gekapert hat. Wann wird dieser Halunke endlich geschnappt und zum Trocknen in die Sonne gehängt?",
"Man munkelt, unser Kaufmann rüstet zusammen mit dem Gouverneur ein Schiff nach Afrika aus – sie wollen Sklaven fangen. Sogar der Geldverleiher soll da seine Finger im Spiel haben. Was soll man sagen, mit Menschenhandel lässt sich eben gutes Geld machen...", // 40
"Man munkelt, unser Gouverneur plant neue Verordnungen, um härter gegen Schmuggel und Piraterie vorzugehen. Aber ich wette, am Ende bedeutet das nur, dass wir Bürger wieder tiefer in die Tasche greifen müssen, während die Beamten sich die Taschen füllen – und ansonsten bleibt alles beim Alten.",
"Was ist nur aus der Welt geworden? Neulich hat unser Medicus, nachdem er einen über den Durst getrunken hatte, erzählt, dass er zu einer Gebärenden gerufen wurde. Die Frau behauptete, der Vater ihres Kindes sei unser Gouverneur! Und dabei ist er verheiratet und hat schon vier Kinder mit seiner Ehefrau. Was wohl aus dem armen Mädchen wird, wenn der Gouverneur erfährt, dass sie so ein loses Mundwerk hat?",
"Unser Gouverneur ist ein ganz schöner Gauner, sag ich dir. Neulich hat einer der Freibeuter eine gekaperte Jacht ins Schlepptau gebracht, und was macht der Gouverneur? Kauft das gute Stück für ein paar Groschen und schenkt sie seiner Frau! Wo bleibt da die Gerechtigkeit, frage ich dich?",
"Neulich ist ein Schiff mit einem Boten des Königs in unserem Hafen eingelaufen. Jeden Tag wird nun die Ankunft des Generalgouverneurs erwartet. Anscheinend ist man in der Hauptstadt mit unserem Gouverneur nicht besonders zufrieden.",
"Man munkelt, dass die französische und die englische Flotte kürzlich gemeinsame Manöver abgehalten haben. Dabei haben sie geübt, wie man feindliche Küstensiedlungen aufspürt, angreift und zerstört.",
"Vor kurzem liefen ein paar Patrouillenschiffe in unseren Hafen ein, und auf zwei von ihnen konnte man noch Spuren eines frischen Gefechts sehen. Man erzählt sich, sie hätten es mit einer besonders starken Piratenflotte zu tun gehabt – sogar ein Galeone soll dabei gewesen sein.",
"Man munkelt, dass vor Kurzem eine feindliche Flotte eine unserer Kolonien angegriffen hat. Allerdings hielten sie sich dabei an die Regeln: Sie stellten ein Ultimatum, blockierten den Hafen und warteten drei Tage ab, bevor sie versuchten, das Fort zu stürmen. Doch der Angriff schlug fehl – das Fort hielt stand. Da ihre Schiffe schwer beschädigt waren, mussten sie schließlich unverrichteter Dinge wieder abziehen.",
"Man munkelt, dass die Aufseher auf einer Plantage kürzlich einen großen Sklavenaufstand verhindert haben. Die Anführer wurden gefasst und zum Tode verurteilt.",
"Man erzählt sich, dass es kürzlich jemandem gelungen ist, ins Büro des Generalgouverneurs einzudringen und dabei streng geheime Dokumente zu stehlen. Das Kuriose daran: Keiner der zehn Wachen hat irgendetwas Verdächtiges bemerkt – bis der Generalgouverneur am Morgen sein Büro betrat.",
"Neulich lief hier ein prächtiges Schiff in unseren Hafen ein. Die Leute erzählen, der Kapitän sei ein ehemaliger Sklave, der mit seinen Freunden von einer Plantage geflohen ist. Ich glaube das allerdings kaum – seine guten Manieren verraten, dass er entweder ein Edelmann oder zumindest ein gebildeter Mensch ist.", // 50
"Man munkelt, dass neulich eine der hiesigen Zigeunerinnen beim Sammeln von Shatun-Kraut erwischt wurde – einer der Hauptzutaten in der sogenannten Serenity-Magie, die von karibischen Satanisten praktiziert wird. So sieht’s aus.",
"Man munkelt, dass eine Frau aus unserer Stadt eine Voodoo-Priesterin ist. Ein Bürger will sie nachts mit ihrem kürzlich verstorbenen Ehemann spazieren gesehen haben.",
"Neulich kam ein holländischer Kapitän in die Taverne und erzählte, dass er südöstlich von Main eine Geisterschiff gesichtet hat – eine Dreimastschoner. Offenbar ist nicht nur der „Fliegende Holländer“ dazu verdammt, ewig über die Meere zu irren.",
"Man erzählt sich, dass der Leuchtturmwärter auf Jamaika kürzlich den Geist der Piratenbrigantine „Rainey“ gesehen hat. Dieses Schiff ist vor zehn Jahren in einer Schlacht gegen ein englisches Geschwader untergegangen. Nur der Kapitän und ein Schiffsjunge, den eine Explosion über Bord schleuderte, haben damals überlebt. Der Kapitän wurde später gefasst, vor Gericht gestellt und gehängt – sein Leichnam baumelte am Pier. Seitdem zieht der Geist der Brigantine jedes Jahr an Port Royal vorbei und salutiert seinem Kapitän.",
"Wir haben gehört, dass ein französischer Kapitän erzählte, ihm sei ein Offizier von einer spanischen Brigg im Traum erschienen – derselbe, den er einen Monat zuvor beim Entern getötet hatte. Der Geist warnte ihn, sein Schiff sei in Gefahr, weil es direkt auf ein Riff zusteuere, das auf französischen Karten nicht verzeichnet ist.",
"Neulich ging in der Stadt das Gerücht um, dass in den Dschungeln irgendein seltsames Wesen aufgetaucht ist. Angeblich hat es eine ganze Herde Schafe gerissen, das Fleisch nicht angerührt, aber das Blut bis auf den letzten Tropfen ausgesaugt. Für mich sind das bloß Ammenmärchen, damit die Kinder nicht zu neugierig werden und sich aus der Stadt schleichen.",
"Man erzählt sich, dass die Spanier bei ihrer letzten Expedition auf dem Festland eine uralte Kultstätte entdeckt haben. In der Nähe fließt ein Bach – wer sich mit seinem Wasser wäscht, dessen schlimmste Wunden heilen in zwei, drei Tagen.",
"Gestern habe ich gehört, dass unser Geldverleiher den Gouverneur beim Kartenspiel so abgezockt hat, dass der ihm als Preis ein Dokument ausstellen musste – damit ist der Geldverleiher jetzt für ein paar Jahre von allen Steuern befreit. So läuft das hier!",
"Vor Kurzem haben Banditen die Tochter eines unserer angesehenen Bürger entführt. Der arme Mann musste sich sogar bei einem Geldverleiher verschulden, um das Lösegeld aufzubringen. Doch dann tauchte ein mutiger junger Kapitän auf, der nicht nur das Mädchen aus den Händen der Banditen befreite, sondern auch gleich den Anführer der Bande gefangen nahm und der Justiz übergab. Der Kommandant meinte damals schon, dieser Bandit sei ein besonders übler Bursche, der viele Sünden auf dem Kerbholz habe. Und stell dir vor: Das Mädchen hat sich prompt in ihren Retter verliebt. Wenn bei den beiden alles gut läuft, könnten sie ein schönes Paar werden. Wobei ich bezweifle, dass der Kapitän lange an Land bleibt.",
"Man erzählt sich, tief im Dschungel von Maina stehen unheimliche steinerne Figuren. Ob das nun Götzen der Ureinwohner sind oder alte Opferstätten, weiß keiner so genau – aber selbst die Indios aus den umliegenden Dörfern trauen sich nicht, ihnen zu nahe zu kommen oder sie zu berühren. Schon seltsam, oder?", // 60
"Unter den Stadtbewohnern hält sich hartnäckig das Gerücht, dass sich irgendwo auf der Insel Piraten verstecken. In den letzten drei Monaten sind rund um die Insel mehrere kleine Boote spurlos verschwunden – von ihnen fehlt jede Spur. Allerdings wurden drei Schiffe gefunden, oder besser gesagt: das, was von ihnen übrig war.",
"Man munkelt, dass die Puffmutter in letzter Zeit auffällig oft in die Kirche geht. An sich nichts Besonderes, aber sie nimmt immer eines ihrer Mädchen mit – und zwar erst, wenn die Kirche schon geschlossen ist. Ein Gelübde ist das eine, aber unser Padre ist eben auch nur ein Mann. Hehe.",
"Man erzählt sich, dass der Pirat namens Langer John auf See ein Boot mit dem Cousin des Gouverneurs gefunden hat. Er hat den Jungen sicher an Land gebracht. Obwohl der Kommandant der Festung bestätigte, dass John ein Pirat ist, verbot der Gouverneur, Langer John anzurühren, und gab ihm sogar noch eine Belohnung für seine Mühe.",
"Man sagt ja, alle Piraten seien Räuber und Mörder, aber ich versichere euch: Das stimmt so nicht. Neulich hat ein durchreisender Händler in der Taverne erzählt, wie der Pirat, den sie Langer John nennen, auf See ein Boot mit dem Cousin eines Gouverneurs gefunden hat. Er hat den Jungen gesund gepflegt, sicher zur Insel gebracht und direkt seinem Verwandten übergeben – und nicht mal einen einzigen Peso dafür verlangt.",
"Man munkelt, dass ein gewisser Erster Maat, Jean Dampier, versucht hat, auf einem Kriegsschiff Seiner Majestät eine Meuterei anzuzetteln. Der Aufstand wurde niedergeschlagen, die tapferen Verschwörer festgenommen und vor ein Kriegsgericht gestellt. Da hatten sie wirklich Pech, muss man sagen.",
"Man munkelt, der älteste Sohn des Geldverleihers habe kürzlich um die Hand der Gouverneurstochter angehalten. Sollte die Hochzeit tatsächlich stattfinden und sich diese beiden Familien zusammentun, dann ist hier richtig was los – das kannst du mir glauben! Schon jetzt halten der Gouverneur und der Geldverleiher die halbe Stadt fest im Griff.",
"Man munkelt, dass unser Gouverneur von unseren Soldaten nicht gerade begeistert ist. Vor etwa einem Monat hat eine Piratenflotte versucht, unsere Stadt einzunehmen. Wäre da nicht zufällig ein tapferer Freibeuter vorbeigekommen, um seine Wasservorräte aufzufüllen – wer weiß, was dann aus der Stadt geworden wäre.",
"Man erzählt sich, dass kürzlich ein englischer Freibeuter auf der Korvette „Sleipnir“ Offiziere von der Fregatte „La Roche“ nach Tortuga gebracht hat. Gerüchten zufolge gab es auf der Fregatte eine Meuterei: Die Verschwörer übernahmen das Schiff und setzten die Offiziere auf einer unbewohnten Insel aus.",
"Neulich ging das Gerücht um, dass ein holländischer Kaper jetzt regelmäßig englische Küstenwachschiffe angreift. Frech segelt er direkt auf die Insel zu, die Wachen nehmen sofort die Verfolgung auf – und dann feuert der Kaper ein paar Breitseiten und entert das Schiff. Gibt die Besatzung der Küstenwache auf, lässt er sie nach dem Leeren des Laderaums einfach laufen. Man munkelt, er könnte so die ganzen Kleinen Antillen unsicher machen.",
"Dem Händler Alex Exville zufolge treibt vor Jamaika ein Piratengeschwader aus vier Schaluppen sein Unwesen – mit einer außergewöhnlich erfahrenen Crew. Wenn man ihm glaubt, konnte er sich mit seinen zwei Galeonen nur mit Mühe vor ihnen retten.", // 70
"Man munkelt, unser Generalgouverneur hat jetzt einen besonders klugen und gerissenen Berater. Unter den Gouverneuren macht schon der Witz die Runde, dass hier nicht der Generalgouverneur das Sagen hat, sondern ein ganzes Duo.",
"Nach ein paar Gläsern zu viel hat der Kommandant der Festung ausgeplaudert, dass bald ein Kriegsgeschwader aus Europa ankommt, um härter gegen die Piraten vorzugehen. Aber wenn du mich fragst, werden die wohl selbst nicht besser sein und sich auch am Plündern und Überfallen beteiligen.",
"Man munkelt, dass sich neulich ein feindlicher Spion in unsere Stadt geschlichen hat. Doch ein Sergeant der Stadtwache hatte Glück und entdeckte ihn. Der Spion wurde festgenommen und ins Gefängnis gesteckt. Zur Belohnung bekam der Sergeant drei Tage Urlaub.",
"Man munkelt, dass vor Kurzem mehrere Tonnen Kupferblech von einer der Werften gestohlen wurden – das Zeug, mit dem man die Schiffe gegen Schiffsbohrwürmer schützt. Wie die das wohl geschafft haben, so eine schwere Ladung unbemerkt wegzuschaffen?",
"Man munkelt, ein Pirat habe auf dem Schafott stehend einen Zettel mit seltsamen Zeichen in die Menge geworfen und gerufen: „Wer das entschlüsselt, wird mein Erbe!“ Tja, da wird wohl jemand richtig Glück haben!",
"Man munkelt, dass ein Geldverleiher vor einem halben Jahr ein Kopfgeld auf einen besonders dreisten Piraten ausgesetzt hat. Nur ein paar Wochen später wurde der Geldverleiher tot in seinem eigenen Haus aufgefunden – geköpft. In der Nähe der Leiche lag eine seltsame Notiz: „Ich habe mich nie geirrt, denn ich konnte die Menschen durchschauen. Doch diesmal habe ich mich getäuscht – und das gleich doppelt.“",
"Man munkelt, dass ein berüchtigter Verbrecher aus dem Gefängnis entkommen ist – auf seinen Kopf ist eine ordentliche Belohnung ausgesetzt. Jetzt durchkämmen unsere Draufgänger die Dschungel, aber wer weiß, vielleicht landen sie am Ende selbst am Spieß bei den Kannibalen...",
"Unser Gouverneur hat sich wohl die Finger schmutzig gemacht. Man hört, der Generalgouverneur hat Wind von seinen Machenschaften bekommen und eine Sonderkommission zur Untersuchung geschickt. Aber wir wissen ja, wie solche Kommissionen arbeiten. Die lassen sich ein paar Mädchen aus dem Bordell kommen, feiern ein Festmahl, schreiben dann einen Bericht, dass alles in bester Ordnung ist und es keine Verstöße gibt. Und dann segeln sie wieder heim und tun weiter nichts – faule Bande...",
"Man erzählt sich, dass neulich jemand im Dschungel eine Armeepatrouille ausgelöscht hat. Die Piraten scheinen wohl gar keine Angst mehr zu haben, wenn sie sich schon an Soldaten herantrauen. Es geht das Gerücht um, der Gouverneur wollte zur Vergeltung zwei Schiffe mit Soldaten zum nächsten Piratennest schicken, mit dem Befehl, alle niederzumachen und keine Gefangenen zu machen. Aber der Kommandant hat ihm diesen Wahnsinn ausgeredet.",
"Man munkelt, der Sohn des Gouverneurs habe den Sohn des Geldverleihers zum Duell herausgefordert – alles nur, weil dieser seiner Verlobten ein unverschämtes Angebot gemacht haben soll. Da beide „Duellanten“ aber Sprösslinge einflussreicher Familien sind, haben die Väter sich geeinigt: Statt mit Pistolen oder Degen sollen die Jungs im Rudern gegeneinander antreten. Der Sohn des Geldverleihers ist allerdings seit jeher ein Schwächling – ich weiß nicht, worauf er da hofft.", // 80
"Man munkelt, dass eine englische Kriegsgesellschaft kürzlich schwere Verluste durch zwei Kaperschiffe unter holländischer Flagge erlitten hat. Entweder waren die Soldaten unerfahren, oder die Kaperfahrer haben sie einfach überrumpelt...",
"Gestern in der Taverne, nach reichlich Rum, erzählte ein Seemann von einem Handelsschiff, das gerade in unseren Hafen eingelaufen ist, dass es irgendwo im Pazifik eine Insel geben soll, auf der echte Drachen leben – und er habe sie mit eigenen Augen gesehen.",
"Gestern erzählte der Kapitän einer Kaperkorvette in der Taverne, dass er gesehen hat, wie zwei Piratenkapitäne mit Degen aufeinander losgegangen sind – nur weil der Kapitän der „Raptor“ die „Weiße Möwe“ als klapprige Nussschale bezeichnet hat. Jetzt gehört die „Raptor“ dem Kapitän der „Weißen Möwe“. Siehst du, große Klappe zahlt sich eben nie aus.",
"Man erzählt sich, dass Piraten neulich ganz in der Nähe unseres Eilands ein Sklavenschiff gekapert haben. Sie haben nur die Frauen mitgenommen, die Männer ließen sie in Ruhe. Scheint, als hätten sie inzwischen ziemlichen Mangel an Frauen.",
"Kürzlich ging das Gerücht um, dass ein spanisches Kriegsgeschwader irgendwo im Süden Afrikas einen Stützpunkt der Piratenrepublik zerstört hat.",
"Man munkelt, dass kürzlich zwei Freibeuter ihre Kräfte gebündelt und eine große Goldmine auf dem spanischen Festland überfallen haben.",
"Man munkelt, ein französischer Freibeuter sei so verrückt geworden, dass er ein Handelsschiff unter englischer Flagge gekapert hat. Und wenn man den Gerüchten glaubt, hat er das nur getan, weil die Tochter des Kapitäns seinen Heiratsantrag abgelehnt hat.",
"Man munkelt, dass der Freibeuter Peter Nord mal wieder danebengegriffen hat. Er hat ein englisches Handelsschiff gekapert, aber das war leer – nur Ballast statt wertvoller Fracht an Bord.",
"Man munkelt, einer der Piratenkapitäne hat ein ordentliches Kopfgeld auf seinen ehemaligen Gehilfen ausgesetzt. Soweit ich gehört habe, soll der Kerl in der Taverne von La Vega eine Kellnerin vergewaltigt und ermordet haben.",
"Man erzählt sich, dass ein Glückspilz es geschafft hat, eines Nachts eine nagelneue spanische Fregatte zu kapern – genau das Schiff, mit dem der Gesandte des spanischen Königs angekommen war. Und das Ganze direkt im Hafen einer spanischen Stadt, mitten im Blickfeld der Kanoniere der Festung! Angeblich war Botschafter Rolandinho del Capiero ziemlich baff, als er am Morgen auf den Balkon des Gouverneurspalastes trat und sein Schiff verschwunden war.", // 90
"Heute hat ein Freibeuter in der Taverne erzählt, dass er kürzlich eine große Flotte spanischer Kriegsschiffe gesehen hat – sie waren auf dem Weg zu einer der englischen Inseln.",
"Man munkelt, ein Gelehrter und Alchemist, der sich kürzlich in unserer Stadt niedergelassen hat, habe eine Substanz entdeckt, die genauso wirkt wie Voodoo-Magie.",
"Man erzählt sich, dass vor ein paar Monaten einer unserer Stadtbewohner Söldner angeheuert hat, um die zu finden und zu töten, die sein Haus überfallen und dabei seine Frau und seinen Sohn ermordet haben. Kürzlich ging das Gerücht um, dass die Leichen dieser Halunken in einer nahegelegenen Bucht gefunden wurden. Die Körper wurden nicht begraben, und die Möwen haben sich an den Knochen gütlich getan.",
"Man munkelt, dass der Kommandant der Festung kürzlich beim Kartenspiel eine ordentliche Summe verloren hat. Trotzdem hat er das Angebot des Geldverleihers ausgeschlagen und keinen Kredit aufgenommen. Woher die Leute nur immer so viel Geld haben, ist mir ein Rätsel.",
"Man munkelt, dass die Bordellbesitzerin dem Kommandanten der Festung ihre Mädchen kostenlos für Liebesdienste überlässt. Im Gegenzug schickt er ihr hin und wieder ein paar junge Soldaten vorbei, damit auch sie ihren Spaß hat.",
};

// Слухи капитанов
string CAPTAIN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Ein gutes Fernrohr ist im Seegefecht Gold wert. Damit kannst du die Stärke des Gegners und deiner eigenen Mannschaft einschätzen und entscheiden, ob du angreifen oder lieber das Gefecht meiden solltest. Durch ein ordentliches Glas erkennst du immer, ob Musketiere in der Entertruppe des Feindes sind, wie viele Kanonen auf dem Deck noch intakt sind, wie groß die Besatzung ungefähr ist und womit die Kanoniere ihre Geschütze laden – so triffst du die richtige Wahl. Und wenn du das Glück hast, ein besonders feines Exemplar zu ergattern, kannst du sogar das Kaliber der feindlichen Kanonen bestimmen.",
"Achte bei einer Seeschlacht immer darauf, womit die Kanonen des Gegners geladen sind. Es ist keine gute Idee, mit vollen Segeln auf ein Schiff zuzufahren, dessen Geschütze mit Kettenkugeln geladen sind – die zerfetzen dir das Segel oder holen im schlimmsten Fall sogar den Mast runter. Genauso töricht ist es, sich einem Schiff zu nähern, das seine Kanonen mit Kartätschen geladen hat – halte lieber Abstand und beschieß es aus der Ferne mit Kugeln oder Bomben.",
"Hütet euch vor Schiffen, die kurz vorm Sinken stehen! Viele Kapitäne, die nichts mehr zu verlieren haben, zünden ihre Pulverkammer an und verwandeln ihr Schiff in einen Branders – und gehen zum Angriff über. Seid ihr unvorsichtig und kommt zu nah heran, fliegt ihr mit ihnen in die Luft. Haltet Abstand zu auseinanderfallenden Schiffen und gebt ihnen lieber aus sicherer Entfernung mit Kanonenkugeln oder Bomben den Rest.",
"Nähern Sie sich niemals einem sinkenden Schiff, Captain! Ein Schiff, das untergeht, kann auch Ihr eigenes in die Tiefe reißen. Wenn Sie dennoch die Ladung und Waren bergen wollen, die beim Untergang an die Oberfläche getrieben wurden, warten Sie, bis das Wrack vollständig verschwunden ist.",
"Unterschätze Kanonenkugeln nicht, Captain! Keine andere Munition fliegt so weit, und auf große Distanz richten sie nicht nur Schaden am Rumpf an, sondern können sogar Kettenkugeln ersetzen. Denk daran: Kanonenkugeln erreichen Ziele, die kein anderes Geschoss trifft.",
"Kanonen oder Kartaunen? Ach, das ist die große Frage und ein ewiges Dilemma! Kanonen laden schneller nach und sind leichter, aber Kartaunen schießen weiter. Du musst also selbst entscheiden, was dir wichtiger ist: schnelle Nachladezeiten und mehr Platz im Laderaum oder doch Reichweite und Präzision beim Schießen.",
"Jage nicht immer den größten Kanonen hinterher, Kollege! Je größer das Kaliber, desto länger dauert das Nachladen und desto schwerer wird dein Schiff. Was bringt dir die dickste Kanone, wenn dein Kahn danach kaum noch manövrierbar ist und im Laderaum kein Platz mehr bleibt? Kleinere Kaliber richten zwar weniger Schaden an, sind aber leichter zu bedienen, schneller nachgeladen und machen dein Schiff nicht unnötig schwer.",
"Ich verrate Ihnen was, Captain, ganz unter uns: Der beste Kanonenkaliber ist der Vierundzwanziger. Das ist die perfekte Mischung aus Gewicht, Nachladegeschwindigkeit und Durchschlagskraft. Nur die Kartaunen schießen weiter. Die Zweiunddreißiger und Sechsunddreißiger hauen zwar ordentlich rein, aber ihre Reichweite ist enttäuschend – und vom Gewicht will ich gar nicht erst anfangen.",
"Im Gefecht, mein Freund, vergiss nicht die Wirkung von Pulverminen! Besonders nützlich sind sie, wenn du dich schnell vom Schlachtfeld zurückziehen musst. Zwei, drei Fässer – und dein ahnungsloser Verfolger landet bei den Fischen! Aber denk daran: Du bist nicht der Einzige mit solchen Tricks. Behalte die Bewegungen deiner Feinde im Auge und verwechsle bloß kein Rumfass mit einer Pulvermine. So ein Fehler könnte dich teuer zu stehen kommen!",
"Vergiss nicht, deine Kanonen regelmäßig auszutauschen, Kollege! Im Gefecht nutzen sich die Geschütze ab, und irgendwann fallen sie aus oder explodieren sogar. Du willst doch nicht mitten in einer langen Schlacht ohne Kanonen dastehen, oder? Und je kleiner das Kaliber, desto kürzer hält das Geschütz. Ich habe allerdings gehört, dass es irgendwo einen verzauberten Talisman gibt, mit dem die Kanonen ewig halten... Aber wo soll man den finden? Ach, das sind wohl nur Seemannsgarn...",
};

// Слухи мещан мужские
string CITIZEN_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Handel zu treiben ist gar nicht so einfach. Fast alle Kolonien stellen die gleichen Waren her, und nur selten findet man irgendwo eine ordentliche Nachfrage nach den hiesigen Schätzen – obwohl du in Europa dafür ein Vermögen bekommen würdest. Wenn du also keinen fähigen Zahlmeister hast oder selbst kein Händchen fürs Feilschen, solltest du dich vielleicht lieber anderweitig versuchen. Wie wäre es zum Beispiel mit einem Dienst beim Gouverneur?",
"Die mächtigste Handelsgesellschaft in der Karibik ist die Niederländische Westindien-Kompanie. Ihr Hauptsitz liegt in Willemstad. Schau dort unbedingt mal vorbei – für fähige Kapitäne gibt es dort oft Aufträge.",
"Wenn du schnell etwas Geld brauchst und ein eigenes Schiff hast, solltest du direkt zum Hafenamt gehen. Dort kannst du dein Schiff vermieten, dich als Eskorte anheuern lassen oder eilige Dokumente transportieren. Aber vergiss nicht: Die Eigenschaften deines Schiffs sind entscheidend. Mit einer lahmen Nussschale wirst du kein Kurier, und mit einem Boot, das kaum größer als eine Schaluppe ist, brauchst du auf lukrative Frachtaufträge gar nicht erst hoffen.",
"Wenn du mit Frachten dein Geld verdienen willst, solltest du wissen: Die Hafenbehörden vergeben nur richtig große Aufträge – dafür brauchst du aber auch ein entsprechend großes Schiff. Hast du nur ein kleines Boot, versuch dein Glück lieber beim örtlichen Händler. Der sucht oft jemanden, der kleinere Warenladungen transportiert.",
"Wenn du durch den Dschungel reist, sei vorsichtig – dort triffst du oft auf feindselige Eingeborene, Banditen oder, falls du dich auf einer feindlichen Insel befindest, sogar auf Patrouillen. Nimm am besten ein paar Offiziere mit – sie können dir im Ernstfall beistehen.",
"Scheuen Sie sich nicht davor, Passagiere mitzunehmen, Captain. In der Stadt findet sich oft jemand, der in eine andere Kolonie reisen möchte – manchmal sogar zwei. Reich werden Sie damit zwar nicht, aber Ihr Ruf wird sich verbessern. Und wenn es sowieso auf Ihrem Weg liegt – wer sagt da nein zu ein paar zusätzlichen Pesos?",
"Für manche Waren und Dienste wird ausschließlich mit Gold-Dublonen bezahlt. Halte also immer ein paar davon in deiner Truhe bereit, sonst entgeht dir vielleicht ein gutes Geschäft. Du kannst zwar beim Geldverleiher Pesos gegen Dublonen tauschen, aber nur in kleinen Mengen. Am besten verlangst du selbst, wann immer möglich, Dublonen als Bezahlung für deine Dienste.",
"Du siehst aus wie ein echter Haudegen. Wenn dein Schiff stark und gut bewaffnet ist, solltest du dich beim Hafenamt als Eskorte für Konvois anheuern lassen. Machst du deinen Job gut, bekommst du bald anspruchsvollere und gefährlichere, aber auch viel lukrativere Aufträge.",
"Wenn ihr die neuesten Neuigkeiten erfahren wollt oder jemanden oder etwas in der Stadt nicht finden könnt, geht zuerst zum Wirt der Taverne – er weiß immer, was hier los ist. Kann er euch nicht weiterhelfen, fragt einfach die Leute auf der Straße. Und wenn das auch nichts bringt, bleibt euch nur, selbst nach der Information, dem Haus oder der Person zu suchen.",
"Wenn du in eine feindliche Stadt gelangen willst, tu das am besten nachts. Leg mit deinem Boot in einer abgelegenen Bucht an und schleiche dich durch den Dschungel. Aber sei auf der Hut – die Patrouillen schlafen nie! Wenn sie dich erwischen, gibt’s Ärger. Am klügsten ist es, direkt in die Taverne zu gehen und dort bis zum Morgen zu bleiben – die Wirte sind meist ziemlich tolerant...",
};

// Слухи мещан женские
string CITIZEN_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Schlag einfachen Leuten, die dich auf der Straße um etwas bitten, nichts ab. Vergiss nicht – jeder kann einmal in Not geraten. Für deine Hilfe wirst du reich belohnt, wenn nicht mit Geld, dann mit einem guten Ruf.",
"Wenn dir an Bord Matrosen fehlen und in der Taverne niemand anzuheuern ist, dann sprich einfach mal die Seeleute auf der Straße an. Manche schließen sich gerne deiner Crew an – oft bringen sie sogar Freunde mit. Mein Mann ist übrigens Kapitän und macht das immer so...",
"Wenn ihr keine Lust habt, als Freibeuter unterwegs zu sein und harmlose Handelsschiffe zu überfallen, könnt ihr euch auch beim Hafenamt oder beim Gouverneur anheuern lassen. Dort gibt es immer genug ehrliche Arbeit für einen fähigen Kapitän – oft riskant, aber gut bezahlt. So verdient ihr euren Lebensunterhalt, sammelt Ruhm und Respekt bei den Kolonisten und müsst kein schlechtes Gewissen haben.",
"Ach, Kapitän, es ist doch kein Geheimnis, dass es auf dem Archipel mehrere Piratensiedlungen gibt. Wie die Behörden es nur zulassen, dass diese Halunken direkt vor unserer Nase leben! In jedem dieser Dörfer gibt es einen Anführer – die nennen ihn Baron. Diese Barone treiben allerlei zwielichtige Geschäfte, und man sagt, sie sitzen auf Bergen von Gold!",
"Wisst Ihr, Kapitän, dass die Engländer jedes Jahr eine große Regatta veranstalten? Stellt Euch vor: Geschickte Kapitäne auf ihren Luggers wetteifern darum, wer am schnellsten den Archipel auf einer Rundstrecke umsegelt! Der Sieger genießt hohes Ansehen und bekommt tolle Preise sowie einen Haufen Geld. Aber um überhaupt eingeladen zu werden, müsst Ihr Euch erst einen Namen als Kapitän machen, der schneller als der Wind segeln kann!",
"Ich habe gehört, irgendwo tief im Dschungel des südlichen Festlands gibt es eine spanische Goldmine, um die herum eine ganze Stadt entstanden ist! Ein befreundeter Kapitän hat dorthin Sklaven gebracht und wurde mit goldenen Nuggets bezahlt! Aber erzähl das bloß niemandem weiter...",
"Im Karibischen Meer gibt es noch viele unerforschte, unbewohnte Inseln. Das erzählen zumindest die Seeleute – und denen kann man glauben. Viele dieser Inseln sind nicht einmal auf den Karten eingezeichnet! Nördlich von Kuba soll es sogar eine geheimnisvolle Insel der Gerechtigkeit geben. Alle, die versucht haben, dorthin zu gelangen, sind nie zurückgekehrt. Vielleicht ist es dort einfach zu schön, um wieder wegzuwollen, oder?",
"Wisst Ihr, Captain, wie viele verzauberte Amulette und magische Schutzzeichen man hier in unseren Gegenden finden kann? Oh, eine ganze Menge! Das ist alles das Erbe der Indianer und der afrikanischen Sklaven. Allerdings wirken die meisten nicht besonders lange – nach ein paar Monaten verlieren sie ihre Kraft, warum auch immer. Aber ich habe schon Talismane gesehen, die ihre Macht nicht verlieren. Gesehen, wohlgemerkt – anfassen durfte ich so einen leider nie...",
"Die Leute hier sind rau und ungehobelt, lauter grobe Kerle. Aber Sie, wie ich sehe, sind ein wahrer Gentleman. Schlagen Sie einer Frau niemals Hilfe aus, wenn sie sie braucht! Die Sitten hier sind barbarisch, wir sind schließlich nicht in Europa. Oft gibt es niemanden, der für die Ehre, Würde oder gar das Leben einer Frau einsteht...",
"Wenn du ein bisschen Geschick in den Händen hast – im Gegensatz zu meinem Mann –, kannst du dir jederzeit selbst Munition zusammenstellen, komplizierte Gerätschaften bauen, Tränke mixen oder sogar einen magischen Talisman herstellen. Alles, was du brauchst, sind die richtigen Zutaten, das passende Werkzeug und natürlich die Rezepte.",
};

// Слухи дворян
string NOBLE_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Geschickter Umgang mit dem Degen kann Ihnen in jeder brenzligen Situation das Leben retten – das kann ich Ihnen versichern, mein Herr. In diesen unruhigen Zeiten sollte jeder, der etwas auf sich hält, sich verteidigen können. Ob Sie nun einen Degen, einen Säbel oder ein schweres Breitschwert bevorzugen, spielt dabei keine Rolle. Vergessen Sie jedoch nicht: Jede Waffe verlangt nach ihrer eigenen Kampftechnik. Mit einer Axt zu stechen ist genauso sinnlos wie mit einem Degen Köpfe abzuschlagen.",
"Ein Duell ist keine Kneipenschlägerei. Wenn du in einem fairen Zweikampf siegst, gewinnst du Ruhm, Ansehen und Respekt. Das kann dir später noch nützlich werden. Aber stürz dich nicht kopflos ins Getümmel – vor allem, wenn du mit dem Degen noch nicht viel Erfahrung hast, haha!",
"Wie andere das sehen, weiß ich nicht, mein Herr, aber ich persönlich bin der Meinung: Es ist besser, eine Waffe wirklich zu meistern, als mit allen nur halbwegs umgehen zu können. Andererseits, wenn Sie Köpfchen und Geschick haben, können Sie lernen, mit jeder Klinge zu kämpfen. Das verschafft Ihnen einen klaren Vorteil gegenüber Ihren Gegnern.",
"Verlass dich im Kampf nicht nur aufs Blocken – ein halbwegs erfahrener Gegner durchbricht deine Verteidigung im Handumdrehen. Lerne zu parieren! Mit einer schnellen, geschickten Bewegung kannst du nicht nur den Angriff abwehren, sondern deinen Feind auch aus dem Gleichgewicht bringen. So eröffnest du dir die perfekte Gelegenheit für einen Konter.",
"Ein Pistole ist ja ganz nett, aber ein besserer Freund als ein gutes Schwert an der Seite war, ist und wird es nie sein. Die Pistole kann versagen, das Pulver kann feucht werden, sie kann dir in der Hand explodieren – und von der Treffgenauigkeit wollen wir gar nicht erst reden. Aber ein Degen – das ist etwas anderes! Nicht umsonst sagt man: Die Kugel ist dumm, die Klinge ist klug!",
"Wenn du allein auf offenem Gelände einer Gruppe Halunken gegenüberstehst, zögere nicht, ständig deine Position zu wechseln, auszuweichen oder auch mal die Flucht zu ergreifen. Diese einfältigen Bastarde haben keine Ahnung von Taktik und jagen ihren Gegnern wie eine Herde Schweine hinterher. Trenne sie voneinander und erledige sie einzeln – ein ehrenwerter Edelmann kann im Alleingang ein ganzes Dutzend ungebildeter Pöbelkerle zur Strecke bringen.",
"Lernen Sie zu schießen, mein Herr! Eine Pistole ist im Kampf eine feine Unterstützung. Verlassen Sie sich nicht nur darauf, aber sie kann Ihnen durchaus aus der Klemme helfen. Und wenn Sie den Umgang mit Schusswaffen richtig meistern, können Sie sogar mit vierläufigen Pistolen umgehen – und glauben Sie mir, so ein Teil überzeugt in jeder Auseinandersetzung.",
"Vergiss nie, immer genug Pulver und Kugeln für deine Pistole dabeizuhaben. Denk daran: Nicht jede Munition passt zu jedem Waffentyp. Versuch besser nicht, eine Schrotflinte mit normalen Kugeln zu laden oder in einen feinen Duellpistole Nägel zu stopfen. Lerne, aus Pulver und Kugeln fertige Patronen herzustellen – das macht das Nachladen deiner Pistolen viel schneller und einfacher.",
"Wenn du dir eine Pistole für den Kampf aussuchst, solltest du immer an die jeweilige Situation denken. Musst du dich auf offenem Gelände gegen eine ganze Bande Halunken behaupten, ist Schrot die beste Wahl – damit kannst du gleich mehrere Gegner mit nur einem Schuss erwischen. Aber Vorsicht: Auch deine eigenen Leute könnten getroffen werden. Für gezielte Schüsse auf größere Entfernung brauchst du natürlich eine Pistole, die mit Kugeln geladen wird.",
"Wenn du dir eine Lieblingsklinge aussuchst, achte darauf, dass ihr Gewicht zu deiner eigenen Kraft passt. Ein schwerer Säbel ist keine gute Wahl, wenn du keine starken Muskeln hast oder schnell ermüdest. Glaub mir, auch mit einem leichten Rapier kannst du freche Halunken, die dir zu nahe kommen, genauso gut in die Schranken weisen. Ein geschickter Stoß, ein gekonntes Parieren und ein schneller Rückzug – das sind die Zutaten für deinen Erfolg in jedem Gefecht!",
};

// Слухи дворянок
string NOBLE_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Schlag einfachen Leuten, die dich auf der Straße um Hilfe bitten, ihre Wünsche nicht ab. Denk daran: Jeder kann einmal in Not geraten. Für eine gute Tat wirst du reich belohnt – vielleicht nicht mit Geld, aber mit einem guten Ruf.",
"Wenn dir an Bord Matrosen fehlen und in der Taverne niemand anzuheuern ist, dann sprich einfach die Seeleute auf der Straße an. Manche schließen sich dir gern an und bringen sogar Freunde mit. Mein Mann ist Kapitän, er macht das immer so...",
"Wenn ihr keine Lust auf Kaperfahrten und das Ausrauben armer Händler habt, könnt ihr euch beim Hafenamt oder direkt beim Gouverneur verdingen. Dort gibt es für ehrliche Kapitäne immer wichtige Aufträge – oft nicht ungefährlich, aber gut bezahlt. So verdient ihr euer Geld auf ehrbare Weise und gewinnt außerdem Ansehen und Respekt unter den Kolonisten.",
"Ach, Kapitän, es ist doch kein Geheimnis, dass es auf dem Archipel mehrere Piratensiedlungen gibt. Wie die Behörden es nur zulassen, dass diese Halunken direkt vor unserer Nase leben! In jedem dieser Dörfer gibt es einen Anführer – die nennen ihn Baron. Diese Barone treiben allerlei zwielichtige Geschäfte, und man sagt, sie sitzen auf Bergen von Gold!",
"Wisst Ihr, Kapitän, dass die Engländer jedes Jahr eine große Regatta veranstalten? Stellt Euch vor: Erfahrene Kapitäne auf ihren Luggers wetteifern darum, wer am schnellsten den Archipel auf einer Rundstrecke umrundet! Der Sieger genießt hohes Ansehen und bekommt tolle Preise sowie eine ordentliche Summe Geld. Aber um überhaupt zur Regatta eingeladen zu werden, müsst Ihr Euch erst als Kapitän beweisen, der sein Schiff schneller als der Wind führen kann!",
"Ich habe gehört, dass irgendwo tief im Dschungel von Südmain ein spanisches Goldbergwerk liegt – und drumherum soll sogar eine ganze Stadt entstanden sein! Ein befreundeter Kapitän hat dorthin Sklaven verkauft, und man hat ihn mit echten Goldnuggets bezahlt! Aber pssst... verrate das bloß niemandem weiter.",
"Im Karibischen Meer gibt es noch viele unerforschte, unbewohnte Inseln. Das erzählen zumindest die Seeleute – und denen kann man glauben. Viele dieser Inseln sind nicht einmal auf den Karten eingezeichnet! Nördlich von Kuba soll es sogar eine geheimnisvolle Insel der Gerechtigkeit geben. Wer versucht hat, dorthin zu gelangen, ist nie zurückgekehrt. Wahrscheinlich ist es dort einfach zu schön, oder?",
"Wisst Ihr, Kapitän, wie viele verzauberte Amulette und magische Talismanen es hier bei uns gibt? Oh, eine ganze Menge! Das ist alles das Erbe der Indianer und der afrikanischen Sklaven. Allerdings wirken die meisten nicht besonders lange – nach ein paar Monaten verlieren sie ihre Kraft aus irgendeinem Grund. Ich habe allerdings schon Talismanen gesehen, die ihre Macht nie verlieren. Gesehen, ja – aber in die Hand nehmen durfte ich so einen leider nie...",
"Das Volk hier ist rau und ungehobelt, lauter grobe Kerle. Aber Sie, Kapitän, wirken wie ein Ehrenmann. Schlagen Sie einer Frau nie Hilfe aus, wenn sie sie braucht! Die Sitten hier sind barbarisch, das ist schließlich nicht Europa. Oft gibt es niemanden, der für die Ehre, Würde oder gar das Leben einer Frau einsteht...",
"Wenn du ein bisschen Geschick in den Händen hast – im Gegensatz zu meinem Mann –, kannst du dir jederzeit selbst Munition zusammenstellen, ein kompliziertes Gerät bauen, Tränke mischen oder sogar einen magischen Talisman herstellen. Alles, was du brauchst, sind die richtigen Zutaten, Werkzeuge und natürlich die passenden Anleitungen.",
};

// Слухи матросов
string SAILOR_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Einen guten Kapitän zu finden, ist gar nicht so einfach, oder was meinst du? Einer, der sich um seine Leute kümmert und pünktlich zahlt? Ein Händler denkt nur ans Geld, dass ihm die Kasse nicht leer wird, und für die Soldaten sind wir bloß Kanonenfutter. Dabei läuft das ganze Schiff doch nur dank uns. Also, pass gut auf deine Matrosen auf, Kapitän – wir sind schließlich auch nur Menschen!",
"Gestern hat unser Käpt’n für die ganze Mannschaft Mädels aus dem Bordell bestellt... Mann, das war ein Spaß! Und den Sold zahlt er immer pünktlich und komplett aus. Abends gibt’s an Bord für jeden eine ordentliche Portion guten Rums, und wer von der Nachtschicht kommt, bekommt sogar zwei. Für unseren Käpt’n würden wir jedem die Kehle durchschneiden! So einen findet man nicht alle Tage!",
"Unser Käpt’n heuert ständig diese Frösche an. Die wissen doch nicht mal, wie man richtig mit dem Tauwerk umgeht! Nee, die Franzosen kommen nie an unsere englischen Seeleute ran... Na gut, ihre Kanoniere sind schon was Besonderes – die wachsen wohl mit der Kanone auf. Aber das Wichtigste an Bord sind doch die Segel, oder, Käpt’n?",
"Wissen Sie, Kapitän, diese Grünschnäbel an Bord gehen mir echt auf die Nerven! Sie können sich das gar nicht vorstellen! Es wäre ja nicht so schlimm, wenn es nur ein paar wären, aber manchmal kommen auf einen erfahrenen Seemann gleich zehn von diesen Dummköpfen! Meiner Meinung nach ist es besser, weniger Matrosen zu haben, dafür aber solche, die ihr Handwerk verstehen. Stopfen Sie hundert Landratten auf einen Lugger – das bringt trotzdem nichts.",
"Ich sag’s dir: Schlechtere Matrosen als in den spanischen Kolonien findest du nirgends. Bis die mit den Segeln und Tauen klarkommen, vergeht mindestens ein Monat! Aber im Nahkampf mit dem Säbel – da macht ihnen keiner was vor. Das muss man ihnen lassen! Wenn also eine heftige Schlacht bevorsteht, sind die Spanier genau die Richtigen – echte Draufgänger!",
"Habt ihr schon gehört, was neulich vor der Küste dieser Insel passiert ist? Auf einem Handelsschiff hat die Mannschaft gemeutert, den Kapitän über Bord geworfen und ist dann spurlos verschwunden. Aber ehrlich gesagt – geschieht ihm recht! Der Kerl war ein geiziger Hund, hat seine Leute um den Lohn betrogen und die Rationen auf ein Minimum gekürzt. Das soll anderen eine Lehre sein, die meinen, sie könnten sich auf Kosten der Matrosen bereichern.",
"Der beste Kapitän ist der, der pünktlich den Sold zahlt, seine Mannschaft nicht hungern oder krank werden lässt, für gute Stimmung mit Rum sorgt und auch an das Vergnügen seiner Leute denkt. Können Sie das von sich behaupten, Captain?",
"Ein Kapitän, der den Wert seiner Mannschaft nicht erkennt, bleibt nicht lange Kapitän. Die Grünschnäbel aus der Taverne taugen nicht halb so viel wie eine eingespielte, erfahrene Crew. Pass auf deine Leute auf, Kapitän – schick sie nicht unnötig ins Kreuzfeuer und geh nur dann zum Entern über, wenn du dir sicher bist, dass ihr gewinnt. Manchmal ist es besser, schamlos zu fliehen, als heldenhaft zu sterben.",
"Ich weiß ja nicht, wie’s bei den anderen ist, aber ich heuere niemals bei einem Kapitän an, der als Geizhals verschrien ist. Bevor wir einen Vertrag unterschreiben, fragen wir immer Freunde und den Wirt, was für ein Mensch der Kerl eigentlich ist. Für einen Geizkragen zu arbeiten – schlimmer geht’s nicht. Ich hab das mal gemacht – da lief ich ständig in zerlumpten Hosen herum.",
"Ich sag’s Ihnen, Captain: Ist ein Matrose satt, gesund, ordentlich gekleidet und hat ein paar Münzen in der Tasche, warten an Land Rum und schöne Frauen auf ihn – dann kämpft er für Sie bis zum letzten Atemzug und reißt jeden Piraten in Stücke. Seine Taue sind immer ordentlich, die Kanonen blitzblank und das Pulver bleibt trocken. Merken Sie sich das! Achten Sie auf die Moral Ihrer Mannschaft!",
};

// Если новостей нет в LSC
string NO_RUMOUR_LSC_TEXT[5] = {
"Es ist langweilig auf unserer Insel. Von welchen Neuigkeiten redet ihr überhaupt?..",
"Was gibt’s Neues? Bis zum nächsten Streit zwischen den Narwalen und den Rivados bleibt hier alles ruhig.",
"Nichts Interessantes los... Aber spannend wird’s erst, wenn die Vorräte zur Neige gehen.",
"Nichts Neues... Bis die Piraten mal wieder einem Clan den Hintern versohlen oder die Clans sich gegenseitig an die Gurgel gehen.",
"Keine Neuigkeiten, kein Klatsch. Zumindest bis zum nächsten Streit zwischen den Clans.",
};
