#define SIMPLE_RUMOUR_NUM	95
#define CITIZEN_RUMOUR_NUM	10

string DEFAULT_TEXT[19] = {
"Mówią, że raz lub dwa razy do roku z Porto Bello wyrusza tak zwana Złota Flota – karawana kilkudziesięciu statków handlowych eskortowanych przez okręty wojenne. Zawsze płyną tą samą, od dawna ustaloną trasą: opuszczają hiszpański port Porto Bello, kierują się na północ do Hawany, a stamtąd przez Atlantyk do Europy. Nietrudno się domyślić, że na pokładach Złotej Floty znajdują się niewyobrażalne skarby.",
"Wiedziałeś, że gdy jakaś flota atakuje kolonię, możesz pomóc ją zdobyć? Wystarczy podpłynąć do okrętu flagowego atakującej eskadry, wysłać szalupę na pokład i dogadać się z admirałem co do warunków.",
"Okazuje się, że gdy jakaś flota atakuje kolonię, możesz pomóc w jej obronie – wystarczy przedostać się przez dżunglę do miasta i porozmawiać z gubernatorem o warunkach wsparcia przeciwko napastnikom.",
"Czasem cenne informacje można zdobyć w tawernie od gości albo obsługi. W końcu każdy przyjezdny najpierw zagląda właśnie do gospody.",
"Jeśli chcesz dostać się do wrogiego miasta, możesz wysiąść w pobliskiej zatoce i przedrzeć się przez dżunglę do bram miasta. Najlepiej jednak zrobić to pod osłoną nocy.",
"Kapitanie, jeśli pojmałeś wrogiego kapitana, nie spiesz się z jego losem! Za bogatego jeńca możesz dostać niezły okup. Albo po prostu wysadź go na jakimś bezludnym brzegu.",
"U nas klimat jest gorący i wilgotny, ale od kwietnia do października zaczyna się pora deszczowa z tropikalnymi ulewami i gwałtownymi sztormami. Nikomu nie życzę znaleźć się wtedy na otwartym morzu!",
"Aby odnieść sukces w handlu, trzeba znać opłacalne szlaki, mieć smykałkę do interesów, a czasem także dobre relacje z właścicielami sklepów. Dobry skarbnik również bardzo ułatwia prowadzenie handlu.",
"Kapitanie, pamiętaj, że w bitwie morskiej najgroźniejszy jest ogień burtowy. Staraj się więc zawsze strzelać do wroga z dział ustawionych na burtach, ale sam unikaj ustawiania się tak, by przeciwnik mógł odpowiedzieć burtowym salwą.",
"Czasem lepiej unikać walki na morzu, gdy wróg ma przewagę. Żeby jednak uciec, trzeba być naprawdę szybkim. Jeśli sytuacja robi się beznadziejna i trzeba ratować się ucieczką, warto wyrzucić część ładunku za burtę – statek stanie się lżejszy, popłynie szybciej i łatwiej zgubisz pościg.",
"Ci, którzy postanowili zostać piratami, mogą zdobyć cenne informacje o bogatych kupcach w tawernie. Jednak nie każdy bywalec karczmy podzieli się wieściami o łatwym łupie. Tylko ktoś z mroczną przeszłością może liczyć na taką przysługę. Choć, jak wiadomo, złoto otwiera wszystkie drzwi.",
"Aby zdobyć przychylność generalnego gubernatora i jednocześnie list kaperski jednego z państw, musisz najpierw udowodnić swoją lojalność, sumiennie służąc gubernatorowi jednej z kolonii tego kraju. Zdarzało się jednak, że sławni piraci zostawali kaprami, po prostu kupując patent od nieuczciwych agentów.",
"Za głowę zuchwałego pirata albo niebezpiecznego rozbójnika władze kolonialne często wyznaczają wysoką nagrodę. Wtedy łowcy przygód z całych Karaibów ruszają za nim w pościg – zarówno na lądzie, jak i na morzu.",
"Życie piratów to niebezpieczna sprawa, dlatego często ukrywali swoje łupy w tajnych miejscach i sporządzali dokładne mapy skarbów. Dziś takie mapy są dość powszechne na archipelagu i można je kupić u różnych podejrzanych typów.",
"Aby sprawnie prowadzić okręt, potrzebujesz doświadczonej załogi. Dobrzy ludzie to prawdziwy skarb, więc dbaj o swoich podczas morskich bitew. Wykwalifikowany medyk pomoże ograniczyć straty, a zapas lekarstw na pokładzie zawsze się przyda.",
"Na średnich i dużych okrętach, oprócz kajuty kapitana, jest jeszcze mesa – świetne miejsce, by zebrać wszystkich oficerów i wydać im potrzebne rozkazy.",
"Bukanierzy zawsze byli znani jako świetni myśliwi i doskonali strzelcy. Ich sekret? Zawsze dbają o swoje uzbrojenie. Pamiętaj więc, żeby kupować naboje do pistoletu i nosić przy sobie jak najlepszą broń.",
"Pamiętaj, że każde twoje działanie wpływa na twoją reputację. Plotki szybko się rozchodzą i ludzie mogą opowiadać o tobie różne rzeczy. Słaba reputacja może utrudnić ci handel, ale za to przyda się podczas abordażu – przeciwnik może się ciebie przestraszyć i poddać bez walki.",
"Pilnuj nastrojów załogi. Jeśli są buntownicze, twoi ludzie mogą w każdej chwili wzniecić bunt. Możesz ich udobruchać pieniędzmi albo rumem. Jak to mówią – lepszy kiepski manewr niż bunt na pokładzie.",
};
/// Если новостей нет .
string NO_RUMOUR_TEXT[SIMPLE_RUMOUR_NUM] = {
"Ostatnio nic ciekawego się nie dzieje. Życie płynie spokojnie i bez zakłóceń. Aż trudno w to uwierzyć!",
"U nas wszystko spokojnie i cicho. Statki zawijają tu rzadko, więc ostatnio nic ważnego się nie wydarzyło.",
"Przybycie twojego statku to teraz temat numer jeden w całym mieście!",
"Nie przypominam sobie, żeby coś szczególnego się tu działo. Nawet bójki w tawernie to u nas rzadkość.",
"Raczej nie opowiem ci nic nowego, od dawna nie słyszałem nic ciekawego...",
"Ech, czasy teraz ciężkie... Nasz gubernator znowu podniósł podatki... Mój sąsiad z dwoma kumplami uciekli do dżungli, jak im zagrozili lochami za zaległości.",  
" co ludziom pozostaje? Albo ruszyć na własną rękę, albo najmować się do śmiałych kapitanów – byle nie siedzieć na więziennym żarciu.",
"Mówią, że żołnierze w garnizonie od prawie roku nie dostają żołdu z Europy. Podobno ostatnio kilku z nich uciekło z fortu. I gdzie oni pójdą? Wiadomo – na trakt, rabować... Skoro im nie płacą, to sami sobie wezmą. Teraz uczciwy człowiek boi się nawet za bramę miasta wyjść.",
"Mówią, że nasz gubernator znów zamówił sobie meble ze Starego Świata, do swojej rezydencji. A połowa żołnierzy w forcie chodzi prawie w łachmanach i liczy groch w zupie na sztuki.",

"Słyszałem też, że pewien oficer garnizonowy sprzedał rodzinne drobiazgi, kupił lugier i niedawno wypłynął w morze. Oczywiście od razu nazwali go dezerterem! Ale co miał zrobić, skoro przełożeni dbają tylko o własny interes?",
"Mówią, że w Europie znowu szykuje się wojna. To pewnie znów podatki i cła pójdą w górę, a uczciwy handel ucierpi. Zwykli ludzie ruszą na trakt, byle dalej od poborców i urzędników. ",
"A kto wybierze morze, ten będzie szukał łaski u Pani Fortuny i uciekał przed Jednonogą... Wojna zawsze idzie w parze z biedą i rozbojem.",
"Słyszałeś? Z Europy przypłynęła nowa eskadra – niby żeby wzmocnić patrole i walczyć z korsarstwem. Ale te patrole od piratów różnią się tylko flagą na grotmaszcie.",

"Jeszcze chwila, a spotkają cię na otwartym morzu, skonfiskują ładunek, a powód zawsze znajdą. Potem próbuj udowodnić, że to nie twoja krowa zjadła owies… Więc kupcy muszą płacić konwojentom i najemnikom za ochronę swoich interesów. A co z tego mamy my? Ano tyle, że rum znowu podrożeje! Niech to wszystko diabli wezmą!",
"Mówią, że w Europie znowu niespokojnie... To znaczy, że znów zaczną tu ściągać uchodźcy i różnej maści awanturnicy. A komu oni tu potrzebni? Wiadomo, dla takich jest tylko jedna droga – albo na trakt, rabować podróżnych, albo na morze, piracić.",

"Heh, a gubernatorzy znowu podniosą podatki na utrzymanie garnizonów. Czy to bandyci w dżungli, czy urzędnicy w eleganckich gabinetach – dla zwykłych ludzi to jedno i to samo: krwiopijcy i rozbójnicy...",
"A słyszeliście o tych rybackich tartanach, które czasem pojawiają się koło Turksów?.. Powiem wam, rybacy nie mają tam czego szukać! W tych wodach nigdy nie było ryb!",

"Przysięgam na mój przeciekający barkas, już nigdy nie napiję się rumu... Tu coś jest zdecydowanie nie tak!",
"U nas w miasteczku zwykle spokojnie, ale ostatnio niedaleko latarni morskiej rozegrała się niezła bitwa. Jeden kapitan handlował tu z miejscowymi przemytnikami, a patrol ich przyłapał na gorącym uczynku!",

"Łatwe pieniądze szczęścia nie dają, zapamiętaj moje słowa! Patrolowe brygi przycisnęły szkuner tego kapitana do brzegu i poszli na abordaż. Kapitan zginął od kuli armatniej, a miejscowych paserów powiesili w forcie. Szkoda tylko marynarzy – wszystkich sprzedano na faktorii. Ech... niech Bóg przebaczy ich grzeszne dusze...",//13
"Mówią, że niedawno pewien angielski kapitan wojskowy pomógł holenderskiemu kupcowi odeprzeć atak piratów. Niezłe rzeczy się dzieją! Ale podobno potem zażądał od kupca nagrody.",
"Mówią, że francuski kapitan wojskowy pomógł samotnemu hiszpańskiemu kupcowi odeprzeć atak piratów. Gdy kupiec chciał mu się odwdzięczyć, kapitan odmówił nagrody. Widać, że są jeszcze szlachetni ludzie w naszych czasach!",
"Słyszałeś, kapitanie? Podobno trzech korsarzy połączyło siły i napadło na konwój hiszpańskich statków handlowych!",
"Mówią, że nasz gubernator niedawno dobrze zapłacił jakiemuś kapitanowi za wytropienie i schwytanie pirackiego statku, który tyle szkód narobił kupcom.",
"Mówią, że nasz gubernator niedawno wysłał ekspedycję etnograficzną na kontynent. Ale szczerze mówiąc, wygląda to raczej na kolejną piracką wyprawę — na pokładzie tych galeonów było mnóstwo uzbrojonych po zęby ludzi. Jak na zwykłą ochronę, to zdecydowanie za dużo najemników.",
"Mówią, że nasz karczmarz w końcu miał szczęście i wygrał niezłą sumkę w karty. Wcześniej ciągle przegrywał.",
"Mówią, że nasz gubernator znów przegrał sporą sumę w kości. Wygląda na to, że zwykli ludzie będą musieli zacisnąć pasa, bo podatki na pewno pójdą w górę.",//20
"Ostatnio krąży plotka, że nasz gubernator jest wściekły na pewnego kapitana, z którym kiedyś był prawie jak brat. Wszystko przez to, że ten kapitan oszukał go przy podziale łupów i nie oddał należnej części.",
"Mówią, że jeden z asystentów naszego gubernatora znów widziano w towarzystwie przemytników. Wygląda na to, że omawiali jakieś swoje ciemne interesy.",
"Mówią, że niedawno pewien korsarz pojmał dwóch pirackich kapitanów. Jednak jeden z nich zmarł z powodu ran odniesionych w walce. Chociaż są też plotki, że ten rzekomo zmarły pirat wykupił się wolnością w zamian za informacje o skarbie. Ot, takie historie...",
"Ostatnio w mieście pojawił się złodziej – już kilka domów okradł, a ani straż miejska, ani wojsko nie mogą go złapać. Ludzie zaczęli się niepokoić, a w zeszłą niedzielę przez to prawie wybili okna w rezydencji gubernatora! Nawet żołnierzy z fortu ściągnęli na pomoc miejskiej straży i ci rozpędzili tłum. Kogoś nawet aresztowali…",
"W naszym mieście pojawił się złodziejaszek. Okrada domy, gdy gospodarze wychodzą za swoimi sprawami, a komendantura nic nie może na to poradzić. Ten złodziej jest nieuchwytny, jakby był duchem...",
"Mówią, że nasz szef portu potrafi załatwić papiery na każdy statek, jaki tylko zechcesz. Ale nie dla każdego – trzeba umieć podejść, a najlepiej znać go osobiście…",
"Mówią, że nasza flota szykuje wyprawę karną przeciwko piratom, którzy ostatnio zupełnie się rozpanoszyli. Do tej ekspedycji mają dołączyć tylko korsarze, a kim są korsarze – sami wiecie. To przecież też piraci... Kruk krukowi oka nie wykole, tak myślę.",
"Mówią, że pewien holenderski kaper gra na dwa fronty. Rabuje zarówno swoich, jak i obcych. Gdyby go tak złapać na gorącym uczynku i powiesić – innym odechciałoby się takich numerów!",
"Mówią, że niedawno z wyprawy wróciła ekspedycja karna i przyprowadziła ze sobą cały konwój zdobycznych statków. Podobno ich ładownie były tak wypchane, że linii wodnej w ogóle nie było widać.",
"Mówią, że pułkownik Fox znów złapał jakiegoś pirata i powiesił go na słońcu na molo w St. John’s. Z dowódcą „morskich lisów” nie ma żartów…",//30
"Mówią, że ostatnio jeden z pirackich hersztów potajemnie odwiedził naszego gubernatora. Najzabawniejsze jest to, że od tamtej pory piraci przestali pojawiać się w naszych wodach, choć wcześniej bywali tu całkiem często.",
"Mówią, że nasz lichwiarz ma tajny układ z piratami. W ciągu tygodnia to już trzeci atak na statki kupców, którym właśnie ten lichwiarz pożyczył pieniądze.",
"Mówią, że w jednej z pobliskich zatok widziano piratów, którzy przenosili jakieś skrzynie z okrętu na szalupę. Ciekawe, co w nich było?",
"Słyszeliście? Niedawno piracka eskadra zaatakowała samotny korwetę naszej marynarki wojennej. Na szczęście obyło się prawie bez strat po naszej stronie, a łotry dostały solidną nauczkę.",
"Mówią, że dwa pirackie tartany napadły na kurierskiego lugra. Lugier się obronił, a jedyną stratą były dwie beczki rumu.",
"Mówią, że podczas burzy w pobliżu sąsiedniej wyspy zatonęła piracka brygantyna i nikt z załogi nie przeżył. Ot, takie historie...",
"Mówią, że na naszych wodach widziano statek pirata zwanego James Hook. Od tego czasu nawet nasi żołnierze wolą nie wychylać się za bramy miasta, a morskie patrole wypływają na morze tylko w trójkę.",
"Mówią, że niedawno w jednej z zatok na wyspie znaleziono statek handlowy. Cała załoga została wybita, a ładunek, kasa okrętowa i dokumenty zniknęły bez śladu. Kolejna ofiara pirata znanego jako Czarny Jack... Ten łotr wymyślił sobie nawet własne piętno: wypalił na ciele kapitana litery „B.J.” i powiesił biedaka na końcu rei. Prawdziwy potwór!",
"Mówią, że niedawno pirat zwany Kulawym Psem znów przejął statek handlowy pełen przypraw. Ciekawe, kiedy w końcu złapią tego łotra i powieszą go na słońcu?",
"Mówią, że nasz kupiec razem z gubernatorem szykuje statek do Afryki – chcą łapać niewolników. Podobno i lichwiarz macza w tym palce. Cóż, handel ludźmi to intratny interes...", // 40
"Mówią, że nasz gubernator szykuje nowe rozporządzenia, żeby mocniej walczyć z przemytem i piractwem. Ale mam wrażenie, że znów skończy się tylko na tym, że mieszkańcy zapłacą więcej, a urzędnicy napełnią sobie kieszenie. W rzeczywistości niewiele się zmieni.",
"Dokąd ten świat zmierza? Nasz medyk ostatnio, po kilku głębszych, wygadał się, że wezwano go do rodzącej kobiety. Ta ponoć wyznała, że ojcem dziecka jest sam gubernator! A przecież to żonaty facet, ma już czwórkę dzieci z prawowitą małżonką. Ciekawe, co spotka tę biedaczkę, kiedy gubernator dowie się, że rozwiązała język...",
"Nasz gubernator to niezły złodziejaszek. Ostatnio jeden z kaperów przyprowadził na holu zdobyczną jacht, a gubernator za grosze ją wykupił i podarował swojej żonie. I gdzie tu sprawiedliwość, pytam?",
"Niedawno do naszego portu zawinął statek z posłańcem od samego króla. W każdej chwili spodziewamy się przyjazdu generała-gubernatora. Wygląda na to, że nasz gubernator nie cieszy się zbytnią sympatią w stolicy.",
"Podobno niedawno francuska i angielska flota przeprowadziły wspólne manewry. Ćwiczyli razem poszukiwanie, zdobywanie i niszczenie nadmorskich osad wyimaginowanego wroga.",
"Ostatnio do naszego portu zawinęło kilka okrętów patrolowych, a dwa z nich nosiły ślady świeżej bitwy. Mówią, że natknęli się na potężną piracką eskadrę, w której był nawet galeon.",
"Mówią, że niedawno jedna z naszych kolonii została zaatakowana przez wrogą eskadrę. Podobno wszystko odbyło się zgodnie z zasadami: postawili ultimatum, zablokowali wyjście z portu i przez trzy dni czekali, zanim spróbowali zdobyć fort. Nic im jednak z tego nie wyszło – fort się obronił, a ich okręty zostały tak uszkodzone, że musieli odpłynąć z niczym.",
"Mówią, że niedawno na jednej z plantacji nadzorcy udaremnili masową ucieczkę niewolników. Przywódców złapano i skazano na śmierć.",
"Mówią, że ostatnio ktoś zdołał zakraść się do gabinetu samego generała-gubernatora i ukraść jakieś bardzo tajne dokumenty. Najzabawniejsze jest to, że żaden z dziesięciu strażników niczego nie zauważył, dopóki rano generał-gubernator nie wszedł do swojego gabinetu.",
"Niedawno do naszego portu zawinął piękny okręt. Mówią, że jego kapitan to były niewolnik, który uciekł z plantacji razem z przyjaciółmi. Szczerze mówiąc, trudno mi w to uwierzyć – po manierach kapitana widać, że to albo szlachcic, albo przynajmniej ktoś dobrze wykształcony.", // 50
"Mówią, że ostatnio przyłapano jedną z miejscowych cyganek na zbieraniu ziela szatana – to podobno jeden z głównych składników magii sereniti, kultu karaibskich satanistów. Ot, takie rzeczy się tu dzieją.",
"Mówią, że jedna z mieszkanek naszego miasta jest kapłanką voodoo. Podobno pewnej nocy ktoś widział ją spacerującą ze swoim niedawno zmarłym mężem.",
"Ostatnio do tawerny wpadł holenderski kapitan i opowiadał, że gdzieś na południowy wschód od Meinu widział trójmasztową szkunerę-ducha. Wygląda na to, że nie tylko „Latający Holender” jest skazany na wieczną tułaczkę po morzach.",
"Mówią, że latarnik na Jamajce niedawno zobaczył ducha pirackiej brygantyny „Reni”. Ten okręt zatonął w bitwie z angielską eskadrą dziesięć lat temu. Z całej załogi przeżyli tylko kapitan i młody majtek, którego eksplozja wyrzuciła za burtę. Kapitana potem złapano, postawiono przed sądem i powieszono, a jego ciało zawisło na nabrzeżu. Od tamtej pory każdego roku duch brygantyny przepływa obok Port Royal i oddaje salut swojemu kapitanowi.",
"Słyszeliśmy, jak pewien francuski kapitan opowiadał, że przyśnił mu się oficer z hiszpańskiego brygu, którego zabił miesiąc wcześniej podczas abordażu. We śnie ten oficer ostrzegł go, że jego statek jest w niebezpieczeństwie, bo płynie prosto na rafę, której nie ma na francuskich mapach.",
"Ostatnio po mieście rozeszła się plotka, że w dżungli pojawiło się jakieś dziwne stworzenie. Podobno wybiło całą trzodę owiec, mięsa nawet nie tknęło, za to krew wyssało do ostatniej kropli. Moim zdaniem to tylko babskie gadanie, żeby dzieciaki nie włóczyły się za bramami miasta.",
"Mówią, że podczas ostatniej wyprawy na Mainę Hiszpanie natknęli się na jakieś pradawne miejsce kultu. Obok płynie strumień – podobno jeśli obmyjesz się jego wodą, nawet najgłębsze rany goją się w dwa-trzy dni.",
"Wczoraj słyszałem, że nasz lichwiarz ograł gubernatora w karty – i to tak sprytnie, że gubernator musiał mu wystawić dokument zwalniający go z podatków na kilka lat. Ot, takie rzeczy się tu dzieją.",
"Niedawno bandyci porwali córkę jednego z naszych szanowanych mieszczan. Biedak nawet pożyczył pieniądze od lichwiarza na okup, ale wtedy pojawił się odważny młody kapitan. Nie tylko odbił dziewczynę z rąk bandytów, ale też schwytał ich przywódcę i oddał go w ręce sprawiedliwości. Komendant mówił wtedy, że ten bandyta to wyjątkowy łotr i ma na sumieniu wiele grzechów. A dziewczyna? Zakochała się w swoim wybawcy. Jeśli między nimi wszystko się ułoży, będzie z nich niezła para. Chociaż nie sądzę, żeby kapitan długo wytrzymał na lądzie.",
"Mówią, że w głębi dżungli na Meinie można natknąć się na dziwaczne kamienne posągi. Nie wiadomo, czy to wizerunki dawnych bogów, czy może stare ołtarze ofiarne, ale nawet miejscowi Indianie z pobliskich wiosek boją się do nich zbliżać, a tym bardziej ich dotykać. Ot, takie rzeczy się tu dzieją.", // 60
"Wśród mieszkańców miasta krąży plotka, że gdzieś na wyspie ukrywają się piraci. W ciągu ostatnich trzech miesięcy w okolicach wyspy zaginęło kilka małych statków i ślad po nich zaginął. Co prawda, trzy jednostki odnaleziono – a raczej to, co z nich zostało.",
"Mówią, że właścicielka burdelu ostatnio często bywa w kościele. Niby nic dziwnego, ale zawsze chodzi tam z jedną ze swoich dziewczyn, i to dopiero po zamknięciu świątyni. Wygląda na to, że śluby ślubami, ale nasz padre też tylko człowiek. He he.",
"Mówią, że pirat zwany Długim Johnem znalazł na morzu szalupę z kuzynem gubernatora. Wyciągnął chłopaka z opresji i odstawił go na wyspę. Choć komendant fortu potwierdził, że John to pirat, gubernator zabronił go ruszać, a nawet zapłacił mu za fatygę.",
"Mówią, że wszyscy piraci to zbóje i mordercy, ale zapewniam cię, że to nie do końca prawda. Ostatnio w tawernie pewien kupiec opowiadał, jak pirat zwany Długim Johnem znalazł na morzu szalupę z kuzynem jakiegoś gubernatora. Zajął się chłopakiem, odstawił go na wyspę i oddał prosto w ręce krewnego, nie biorąc za to nawet grosza.",
"Mówią, że pewien pierwszy oficer, niejaki Yann Dampier, próbował wzniecić bunt na okręcie królewskiej marynarki. Bunt został szybko stłumiony, a śmiałków pojmano i postawiono przed sądem wojskowym. Cóż, nie mieli szczęścia.",
"Mówią, że najstarszy syn lichwiarza niedawno oświadczył się córce gubernatora. Jeśli naprawdę dojdzie do tego ślubu i ich rodziny się połączą, to dopiero zacznie się zamieszanie! Już teraz gubernator i lichwiarz trzymają całe miasto żelazną ręką.",
"Mówią, że nasz gubernator nie jest zbyt zadowolony z naszych żołnierzy. Ledwie miesiąc temu piraci próbowali zdobyć nasze miasto. Gdyby nie odważny korsarz, który przypadkiem zawinął do portu po świeżą wodę, nie wiem, co by się z nami stało.",
"Mówią, że niedawno angielski kaper na korwecie „Sleipnir” przywiózł na Tortugę oficerów z fregaty „La Roche”. Podobno na tej fregacie wybuchł bunt – spiskowcy przejęli okręt, a oficerów porzucili na bezludnej wyspie.",
"Ostatnio rozeszła się wieść, że pewien holenderski kaper upodobał sobie atakowanie angielskich okrętów straży przybrzeżnej. Bezczelnie podpływa pod wyspę, strażnicy rzucają się mu naprzeciw, a on oddaje kilka salw burtowych i od razu idzie na abordaż. Jeśli załoga straży się poddaje, to tylko opróżni im ładownię i puszcza wolno, gdzie chcą. Mówią, że w ten sposób może przejść przez wszystkie Małe Antyle.",
"Kupiec Alex Exvil twierdzi, że w okolicach Jamajki grasuje piracka eskadra złożona z czterech szalup, załoga podobno wyjątkowo doświadczona. Jeśli wierzyć jego słowom, ledwo udało mu się uciec przed nimi, choć miał dwa galeony.", // 70
"Mówią, że nasz generał-gubernator dorobił się bardzo sprytnego i przebiegłego doradcy. Wśród innych gubernatorów już żartują, że to nie generał-gubernator rządzi, tylko cały duet.",
"Po kilku głębszych komendant fortu wygadał się, że wkrótce z Europy przypłynie eskadra wojenna, żeby mocniej walczyć z piratami. Choć mam wrażenie, że ta eskadra sama też zacznie łupić i napadać, jak wszyscy inni.",
"Mówią, że ostatnio do naszego miasta zakradł się szpieg wroga. Na szczęście jeden z sierżantów straży miejskiej go zauważył. Szpiega aresztowano i zamknięto w lochu, a sierżant dostał w nagrodę trzy dni urlopu.",
"Mówią, że niedawno z jednej ze stoczni skradziono kilka ton blachy miedzianej, którą wykorzystuje się do ochrony statków przed szkutnikami. Jak oni w ogóle zdołali wynieść taki ciężar?",
"Mówią, że pewien pirat, stojąc na szafocie, rzucił w tłum kartkę z tajemniczymi znakami i powiedział: „Kto to rozszyfruje, zostanie moim spadkobiercą”. Ech, komuś się poszczęści!",
"Mówią, że pół roku temu pewien lichwiarz wyznaczył nagrodę za głowę wyjątkowo zuchwałego pirata. Kilka tygodni później znaleziono lichwiarza martwego w jego własnym domu, bez głowy. Niedaleko ciała leżała dziwna notatka: „Nigdy się nie myliłem, bo zawsze przejrzałem ludzi na wylot, ale tym razem pomyliłem się – i to dwa razy.”",
"Mówią, że z więzienia uciekł groźny recydywista, a za jego schwytanie wyznaczono niezłą nagrodę. Teraz miejscowi śmiałkowie przeczesują dżunglę, ale oby tylko sami nie trafili na rożen u kanibali...",
"Chyba nasz gubernator nieźle się obłowił. Mówią, że generał-gubernator dowiedział się o jego przekrętach i wysłał specjalną komisję, żeby wszystko dokładnie zbadać. Ale wiemy, jak to się zwykle kończy. Zaproszą panienki z burdelu, zrobią sobie ucztę, a potem w raporcie napiszą, że wszystko w porządku, żadnych nieprawidłowości. I wrócą na swoje wygodne posadki, darmozjady...",
"Mówią, że ktoś niedawno wyciął w dżungli cały patrol wojskowy. Wygląda na to, że piraci już zupełnie przestali się bać, skoro atakują żołnierzy. Krąży plotka, że w odwecie gubernator chciał wysłać dwa okręty z desantem do najbliższej pirackiej kryjówki z rozkazem nie brać jeńców i wszystkich wybić, ale komendant odradził mu ten szalony pomysł.",
"Mówią, że syn gubernatora wyzwał na pojedynek syna lichwiarza, bo ten ośmielił się złożyć niestosowną propozycję jego narzeczonej. Ale że obaj są dziećmi wpływowych ludzi, ojcowie dogadali się, że zamiast strzelać i pojedynkować się na szpady, będą rywalizować w wyścigu łodzi. Syn lichwiarza od zawsze był cherlawy, nie wiem, na co on liczy.", // 80
"Mówią, że niedawno angielska eskadra wojenna poniosła spore straty w starciu z dwoma korsarskimi okrętami pod holenderską banderą. Albo żołnierze byli nieprzygotowani, albo korsarze zaatakowali z zaskoczenia...",
"Wczoraj w tawernie, po kilku głębszych, pewien marynarz z handlowego statku, który niedawno zawinął do naszego portu, zarzekał się, że gdzieś na Pacyfiku jest wyspa zamieszkana przez żywe smoki – i że widział je na własne oczy.",
"Wczoraj w tawernie kapitan korsarskiego korwetu opowiadał, jak dwóch pirackich kapitanów pojedynkowało się na szpady. Wszystko przez to, że kapitan „Raptora” nazwał „Białego Łabędzia” lichą łajbą. Teraz „Raptor” należy do kapitana „Białego Łabędzia”. Widać, że zuchwałość rzadko popłaca.",
"Mówią, że niedaleko naszej wyspy piraci ostatnio przechwycili statek handlarzy niewolników. Zabrali tylko kobiety, a mężczyzn zostawili w spokoju. Wygląda na to, że piratom bardzo brakuje kobiet.",
"Ostatnio krąży plotka, że gdzieś na południu Afryki hiszpańska eskadra wojenna rozbiła bazę pirackiej republiki.",
"Mówią, że niedawno dwóch korsarzy połączyło siły i obrabowało dużą kopalnię złota na hiszpańskim Mainie.",
"Mówią, że pewien francuski korsarz tak oszalał, że przejął statek handlowy pod angielską banderą. Podobno zrobił to dlatego, że córka kapitana tego statku odrzuciła jego oświadczyny.",
"Mówią, że kaper Peter Nord znowu się nie popisał. Przechwycił angielski statek handlowy, ale okazało się, że płynął pusty. Zamiast ładunku miał tylko balast.",
"Mówią, że jeden z pirackich hersztów wyznaczył sporą nagrodę za głowę swojego dawnego pomocnika. Podobno ten drań zgwałcił i zamordował kelnerkę w tawernie w La Vedze.",
"Mówią, że pewien szczęściarz pewnej nocy zdołał przejąć nowiutki hiszpański fregat, którym przypłynął królewski wysłannik z Hiszpanii. Stało się to na kotwicowisku hiszpańskiego portu, tuż pod nosem fortecznych artylerzystów. Podobno ambasador Rolandinho del Capiero nieźle się zdziwił, gdy rano wyszedł na balkon pałacu gubernatora i nie zobaczył swojego fregatu.", // 90
"Dziś w tawernie pewien kaper opowiadał, że niedawno widział dużą eskadrę hiszpańskich okrętów wojennych, które płynęły w stronę jednej z angielskich wysp.",
"Mówią, że pewien uczony alchemik, który niedawno osiedlił się w naszym mieście, zdobył substancję działającą niemal tak samo jak magia voodoo.",
"Mówią, że kilka miesięcy temu jeden z mieszkańców naszego miasta wynajął najemników, żeby odnaleźli i zabili tych, którzy napadli na jego dom i zamordowali żonę oraz syna. Ostatnio rozeszła się wieść, że ciała tych drani znaleziono w jednej z zatok niedaleko stąd. Zwłoki leżały porzucone, a mewy ucztowały na ich kościach.",
"Mówią, że ostatnio dowódca fortu przegrał sporo pieniędzy w karty, ale mimo to nie skorzystał z usług miejscowego lichwiarza, chociaż ten chętnie oferował mu pożyczkę. Skąd ludzie biorą takie sumy? Tego już nikt nie wie.",
"Mówią, że właścicielka burdelu pozwala komendantowi fortu korzystać z jej dziewczyn za darmo, a w zamian dostaje od niego od czasu do czasu młodych żołnierzy na własną zabawę.",
};

// Слухи капитанов
string CAPTAIN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Dobra luneta to prawdziwy skarb podczas morskiej bitwy. Dzięki niej możesz ocenić siły wroga i swojej załogi, a potem zdecydować, czy warto atakować, czy lepiej unikać walki. Przez porządną lunetę zobaczysz, czy w oddziale abordażowym przeciwnika są muszkieterzy, ile dział zostało na pokładzie artyleryjskim, oszacujesz liczebność załogi, sprawdzisz, czym kanonierzy ładują armaty – i podejmiesz właściwą decyzję. A jeśli uda ci się zdobyć wyjątkowy model, rozpoznasz nawet kaliber wrogich dział.",
"Podczas bitwy morskiej zwracaj uwagę, czym załadowane są działa przeciwnika. Nie pędź na pełnych żaglach w stronę wroga, jeśli jego armaty mają załadowane łańcuchowe kule – rozerwą ci żagle na strzępy, a może nawet zestrzelą maszt. Równie lekkomyślne jest podpływanie blisko do okrętu, którego działa są nabite kartaczem – lepiej trzymaj się z dala i ostrzeliwuj go kulami armatnimi lub bombami.",
"Uważaj na statki, które są o krok od zatonięcia! Wielu kapitanów, widząc, że nie mają już nic do stracenia, podpala magazyn prochu i zamienia swój okręt w pływającą bombę, ruszając na taran. Jeśli podejdziesz zbyt blisko, możesz wylecieć w powietrze razem z nimi. Trzymaj się z dala od rozpadających się statków i dobijaj je kulami armatnimi lub bombami z bezpiecznej odległości.",
"Nigdy nie zbliżaj się do tonącego statku, kapitanie! Zatonąca jednostka może wciągnąć pod wodę także twój okręt. Jeśli chcesz zebrać towary, które wypłynęły z ładowni zatopionego statku, poczekaj, aż całkowicie zniknie pod powierzchnią.",
"Nie lekceważ kul armatnich, kapitanie! Żaden inny pocisk nie dorówna im zasięgiem, a z dużej odległości potrafią nie tylko uszkodzić kadłub wroga, ale też z powodzeniem zastąpić kartacze. Pamiętaj, kule sięgną tam, gdzie żaden inny pocisk nie doleci.",
"Armaty czy kolubryny? Ach, odwieczne pytanie i trudny wybór! Armaty szybciej się ładują i są lżejsze, ale kolubryny strzelają dalej. Musisz więc zdecydować, co dla ciebie ważniejsze – szybkie przeładowanie i więcej miejsca w ładowni, czy może celność i zasięg ognia.",
"Nie ma co ścigać się za największymi kalibrami dział, kolego! Im większe działo, tym dłużej trwa jego przeładowanie i tym więcej waży. Jaki sens montować największy kaliber, jeśli przez to statek staje się ociężały i do ładowni nic już nie wejdzie? Mniejsze działa może i zadają mniej obrażeń, ale są łatwe w obsłudze, szybko się je przeładowuje i nie obciążają statku zbędnym balastem.",
"Powiem ci w zaufaniu, kapitanie: najlepszy kaliber dział to dwudziestka czwórka. Idealnie łączy wagę armaty, szybkość ładowania i siłę ognia, a zasięgiem ustępuje tylko kulbrynom. Działa trzydziestki dwójki i trzydziestki szóstki są oczywiście potężne, ale ich zasięg pozostawia wiele do życzenia. O wadze nawet nie wspomnę.",
"W walce, kolego, nie zapominaj o skutecznych minach prochowych. Szczególnie przydają się, gdy trzeba szybko wycofać się z bitwy. Dwa-trzy beczki i nieostrożny przeciwnik idzie na dno! Ale pamiętaj, że nie tylko ty wpadasz na takie pomysły – obserwuj ruchy wrogów i nie pomyl beczki z rumem z miną prochową. Taka pomyłka może cię słono kosztować!",
"Nie zapominaj co jakiś czas wymieniać działa, kolego! W trakcie walki armaty się zużywają, a to może prowadzić do ich awarii, a nawet wybuchu. Chyba nie chcesz zostać bez uzbrojenia podczas długiej bitwy? Im mniejszy kaliber, tym krócej działa wytrzymują. Słyszałem jednak plotki o zaczarowanym amulecie, który sprawia, że armaty na statku nigdy się nie psują... Ale gdzie coś takiego znaleźć? Ehh, pewnie tylko bajki...",
};

// Слухи мещан мужские
string CITIZEN_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Handel to niełatwe zajęcie. Prawie wszystkie kolonie produkują te same towary, więc trudno znaleźć miejsce, gdzie lokalne dobra naprawdę są w cenie – choć w Europie zarobiłbyś na nich fortunę. Jeśli nie masz porządnego skarbnika albo sam nie jesteś mistrzem targowania, lepiej spróbuj szczęścia gdzie indziej. Na przykład zaciągnij się do gubernatora…",
"Najpotężniejszą organizacją handlową na Karaibach jest Holenderska Kompania Zachodnioindyjska. Jej siedziba mieści się w Willemstadzie. Jeśli będziesz w okolicy, koniecznie tam zajrzyj – często mają ciekawe zlecenia dla sprytnych kapitanów.",
"Jeśli pilnie potrzebujesz zarobić trochę grosza i masz własny statek, skieruj się do zarządu portu. Tam mogą wynająć twoją jednostkę, zatrudnić cię do eskorty albo powierzyć przewóz pilnych dokumentów. Pamiętaj jednak o możliwościach swojego statku – na powolnej krypie nie zostaniesz kurierem, a mając łajbę niewiele większą od łódki, raczej nie licz na poważne zlecenia.",
"Jeśli chcesz zarabiać na frachcie, pamiętaj, że w urzędach portowych dostaniesz poważne zlecenia, ale potrzebny jest do tego odpowiedni statek. Jeśli twoja jednostka jest niewielka, spróbuj szczęścia u miejscowego kupca – często wynajmuje statki do przewozu mniejszych partii towaru.",
"Podróżując przez dżunglę, zachowaj ostrożność – często można tam natknąć się na nieprzyjaznych Indian, bandytów, a na wrogiej wyspie także na patrol. W takich wyprawach warto zabrać ze sobą oficerów – pomogą ci, jeśli dojdzie do starcia.",
"Nie wzbraniaj się przed przewożeniem pasażerów, kapitanie. W mieście często znajdzie się ktoś, kto chce dostać się do innej kolonii. Na tym fortuny nie zbijesz, ale zyskasz dobrą opinię. A jeśli masz po drodze – czemu nie dorobić paru dodatkowych peso?",
"Za niektóre towary i usługi płaci się wyłącznie złotymi dublonami. Zawsze trzymaj trochę tych monet w swojej skrzyni, bo inaczej możesz przegapić dobrą okazję. Peso da się wymienić na dublony u lichwiarza, ale tylko w niewielkich ilościach. Dlatego, jeśli możesz, żądaj zapłaty za swoje usługi właśnie w dublonach.",
"Wyglądacie na prawdziwego wojaka. Jeśli macie solidny, dobrze uzbrojony okręt, polecam zgłosić się do portowej administracji i zaciągnąć się do ochrony konwojów. Jeśli się sprawdzicie, dostaniecie potem trudniejsze i bardziej ryzykowne, ale za to znacznie lepiej płatne zlecenia.",
"Jeśli chcesz dowiedzieć się, co nowego słychać w mieście, albo nie możesz czegoś lub kogoś znaleźć, zajrzyj najpierw do właściciela tawerny – on zawsze wie, co się dzieje. Jeśli on nie będzie mógł ci pomóc, popytaj ludzi na ulicach. A jeśli i to nie przyniesie efektu, pozostaje ci już tylko samodzielnie szukać informacji, domu lub osoby, której potrzebujesz.",
"Jeśli musisz dostać się do wrogiego miasta, najlepiej spróbować nocą – zacumuj w zatoce z dala od fortu i przejdź przez dżunglę. Ale uważaj, patrole nie śpią! Jeśli cię złapią, możesz mieć poważne kłopoty. Najlepiej od razu skieruj się do tawerny i przeczekaj tam do rana – barmani są zwykle wyrozumiali...",
};

// Слухи мещан женские
string CITIZEN_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Nie odmawiaj pomocy zwykłym ludziom, którzy proszą cię o coś na ulicy. Pamiętaj – każdy może kiedyś znaleźć się w potrzebie. Dobro, które okażesz, wróci do ciebie z nawiązką – jeśli nie w pieniądzach, to w dobrej opinii.",
"Jeśli brakuje ci marynarzy na statku, a w tawernie nie ma nikogo do zaciągu, rozejrzyj się po ulicach – czasem znajdziesz tam chętnych do załogi. Niektórzy przyprowadzą nawet kolegów. Mój mąż jest kapitanem i zawsze tak robi…",
"Jeśli nie masz ochoty na korsarstwo i rabowanie statków biednych kupców, możesz zatrudnić się w porcie albo u gubernatora. Tam zawsze znajdzie się poważne zadanie dla uczciwego kapitana, często wymagające odwagi i gotowości do ryzyka. Zarobki też są całkiem niezłe. Zyskasz nie tylko pieniądze, ale też szacunek i sławę wśród mieszkańców kolonii.",
"Oj, kapitanie, wszyscy wiedzą, że na archipelagu jest kilka pirackich osad. Jak to możliwe, że władze pozwalają tym rzezimieszkom mieszkać tak blisko nas? Każda taka osada ma swojego przywódcę – nazywają go baronem. Ci baronowie zajmują się różnymi szemranymi interesami, a złota, mówią, mają całe góry!",
"Wiecie, kapitanie, że Anglicy co roku organizują wielką regatę? Wyobraźcie sobie – doświadczeni kapitanowie na lugrach ścigają się, kto szybciej opłynie archipelag wyznaczoną trasą! Zwycięzca zdobywa szacunek, świetne nagrody i sporo pieniędzy. Ale żeby dostać zaproszenie na regatę, trzeba najpierw udowodnić, że potrafi się prowadzić statek szybciej niż wiatr!",
"Słyszałam, że gdzieś na południowym Mainie, głęboko w dżungli, Hiszpanie mają kopalnię złota, a wokół niej wyrosło całe miasto! Znajomy kapitan woził tam niewolników na sprzedaż i zapłacili mu za to złotymi samorodkami! Tylko nikomu o tym nie mów...",
"Na Morzu Karaibskim wciąż jest mnóstwo nieodkrytych, bezludnych wysp. Tak mówią marynarze, a im można wierzyć. Wiele z tych wysp nie znajdziesz nawet na mapach! Podobno na północ od Kuby leży tajemnicza Wyspa Sprawiedliwości. Każdy, kto próbował się tam dostać, już nie wrócił. Może to dlatego, że jest tam aż tak dobrze, co?",
"Wiecie, kapitanie, ile w naszych stronach można znaleźć zaczarowanych amuletów i magicznych talizmanów? Oj, naprawdę sporo! To wszystko spuścizna po Indianach i niewolnikach z Afryki. Szczerze mówiąc, większość z nich działa tylko przez kilka miesięcy – potem ich moc jakby znika. Ale widziałam też talizmany, które nie tracą swojej siły. Chociaż tylko widziałam – nawet nie pozwolili mi ich dotknąć...",
"Ludzie tutaj są szorstcy i nieokrzesani, sami twardziele. Ale pan, widzę, to prawdziwy dżentelmen. Nigdy nie odmawiaj pomocy kobiecie, jeśli jej potrzebuje! Zwyczaje tu dzikie, to przecież nie Europa. Często nie ma komu stanąć w obronie kobiecego honoru, godności, a nawet życia...",
"Jeśli masz trochę smykałki do majsterkowania, a nie dwie lewe ręce jak mój mąż, to zawsze poradzisz sobie ze zrobieniem amunicji, złożeniem skomplikowanego urządzenia, uwarzeniem mikstury czy nawet stworzeniem magicznego amuletu. Wystarczy mieć odpowiednie składniki, narzędzia i oczywiście przepisy.",
};

// Слухи дворян
string NOBLE_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Zręczne posługiwanie się szpadą może uratować ci życie w każdej opresji – mówię to z pełnym przekonaniem, panie. W tych niespokojnych czasach każdy szanujący się człowiek powinien umieć się obronić. Nieważne, czy wybierzesz rapier, szablę czy ciężki pałasz. Pamiętaj jednak, że każde z tych ostrzy wymaga innej taktyki – nie ma sensu próbować dźgać toporem, tak samo jak nie da się ścinać głów rapierem.",
"Pojedynek to nie zwykła bójka w ciemnej uliczce. Wygrywając uczciwy pojedynek, zyskujesz sławę, poważanie i szacunek. To może się przydać w przyszłości. Ale nie warto rzucać się na każdego bez powodu, zwłaszcza jeśli nie masz wprawy w szermierce, ha, ha!",
"Nie wiem, jak inni, panie, ale moim zdaniem lepiej perfekcyjnie opanować jeden rodzaj broni, niż być przeciętnym we wszystkich. Choć jeśli masz głowę na karku i sprawne ręce, możesz nauczyć się walczyć każdym rodzajem ostrza. To da ci wyraźną przewagę nad przeciwnikami.",
"Nie polegaj w walce wyłącznie na blokowaniu ciosów – każdy choć trochę doświadczony przeciwnik prędzej czy później przebije twoją obronę. Naucz się parować ataki – wtedy twoja zręczność zaskoczy wroga i nie będzie miał na to odpowiedzi. Dobrze wykonany, szybki ruch pozwoli ci nie tylko odeprzeć uderzenie, ale też wytrącić przeciwnika z równowagi i otworzyć drogę do kontrataku.",
"Pistolet to rzecz przydatna, ale nie znajdziesz lepszego przyjaciela niż porządna szabla u boku. Pistolet może zawieść: proch zawilgotnieje, broń nie wypali albo nawet wybuchnie w dłoni, a celność... szkoda gadać. Co innego szpada! Nie bez powodu mawiają: kula głupia, a klinga mądra!",
"Jeśli stoisz samotnie na otwartym terenie naprzeciwko bandy łotrów, nie wahaj się zmieniać pozycji, uskakiwać i wycofywać się. Te tępe dranie nie mają pojęcia o taktyce walki – gonią za przeciwnikiem jak świnie za żołędziami. Rozdzielaj ich i eliminuj jednego po drugim – szlachetny dżentelmen potrafi sam położyć trupem dziesięciu nieokrzesanych prostaków.",
"Ucz się strzelać, panie! Pistolet to przydatna rzecz w walce. Nie warto polegać na nim całkowicie, ale potrafi naprawdę pomóc. A jeśli opanujesz sztukę strzelania do perfekcji, będziesz mógł sprawnie posługiwać się czterolufowymi pistoletami – a te, uwierz mi, to poważny argument w każdej kłótni.",
"Zawsze miej przy sobie zapas prochu i nabojów do swojego pistoletu. Pamiętaj, że nie każdy rodzaj amunicji pasuje do każdej broni. Nie próbuj ładować kartaczownicy zwykłymi kulami ani wsypywać posiekanych gwoździ do eleganckiego pistoletu pojedynkowego. Naucz się robić naboje z kul i prochu – znacznie ułatwią i przyspieszą przeładowywanie broni.",
"Wybierając pistolet do walki, zwróć uwagę na to, z kim i gdzie będziesz się bić. Jeśli czeka cię starcie z grupą łotrów na otwartym terenie, najlepiej sprawdzi się broń na śrut – jednym strzałem możesz trafić kilku przeciwników naraz. Uważaj jednak, żeby nie zranić swoich. Do celnego strzelania na większą odległość przyda się pistolet ładowany kulami.",
"Wybierając swój ulubiony rodzaj broni białej, pamiętaj, by dopasować jej wagę do własnych możliwości. Nie ma sensu sięgać po ciężką szablę, jeśli nie masz siły byka i szybko się męczysz. Uwierz mi, lekka rapiera potrafi być równie skuteczna w walce z bezczelnymi łajdakami, którzy czyhają na twoje życie i honor. Zwinny pchnięcie, sprawne parowanie, szybki unik – to właśnie klucz do zwycięstwa w każdej potyczce!",
};

// Слухи дворянок
string NOBLE_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Nie odmawiaj pomocy zwykłym ludziom, którzy proszą cię o coś na ulicy. Pamiętaj, każdy może kiedyś znaleźć się w potrzebie. Dobro zawsze wraca – jeśli nie w złocie, to w dobrej opinii.",
"Jeśli brakuje ci marynarzy na statku, a w tawernie nie ma nikogo do zaciągu, spróbuj popytać ludzi na ulicach. Niektórzy chętnie dołączą do załogi, a czasem przyprowadzą też znajomych. Mój mąż jest kapitanem i zawsze tak robi…",
"Jeśli nie masz ochoty na korsarstwo i rabowanie biednych kupców, możesz zatrudnić się w porcie lub u gubernatora. Tam zawsze znajdzie się poważne zadanie dla uczciwego kapitana, często wymagające odwagi. Zarobki są całkiem przyzwoite, więc nie wyjdziesz na tym źle, a przy okazji zyskasz szacunek i sławę wśród kolonistów.",
"Kapitanie, to żadna tajemnica, że na archipelagu jest kilka pirackich osad. Jak to możliwe, że władze pozwalają tym rzezimieszkom mieszkać tak blisko nas? Każda taka osada ma swojego przywódcę – nazywają go baronem. Ci baronowie zajmują się różnymi szemranymi interesami, a złota, mówią, mają całe góry!",
"Wiecie, kapitanie, że Anglicy co roku organizują wielką regatę? Wyobraźcie sobie – doświadczeni kapitanowie na lugrach ścigają się, kto szybciej opłynie cały archipelag wyznaczoną trasą! Zwycięzca zyskuje szacunek, świetne nagrody i sporo pieniędzy. Ale żeby dostać zaproszenie na regatę, trzeba najpierw udowodnić, że potrafi się prowadzić statek szybciej niż wiatr!",
"Słyszałam, że gdzieś na południowym Mainie, głęboko w dżungli, Hiszpanie mają kopalnię złota, a obok niej wybudowali całe miasto! Mój znajomy kapitan woził tam niewolników na sprzedaż i zapłacono mu za to złotymi samorodkami! Tylko nikomu o tym nie mów...",
"Na Morzu Karaibskim wciąż jest mnóstwo nieodkrytych, bezludnych wysp. Tak mówią marynarze, a im można ufać. Wiele z tych wysp nie znajdziesz nawet na mapach! Podobno na północ od Kuby leży tajemnicza Wyspa Sprawiedliwości. Każdy, kto próbował się tam dostać, już nie wrócił. Może to dlatego, że jest tam tak dobrze, co?",
"Wiecie, kapitanie, ile tu u nas można znaleźć zaczarowanych amuletów i magicznych talizmanów? Och, naprawdę mnóstwo! To wszystko spuścizna po Indianach i afrykańskich niewolnikach. Szkoda tylko, że większość z nich działa bardzo krótko – ich moc słabnie już po kilku miesiącach. Chociaż... widziałam kiedyś talizman, który wcale nie tracił swojej siły. Ale tylko widziałam – nawet nie pozwolili mi go dotknąć...",
"Ludzie tutaj są szorstcy i nieokrzesani, sami twardziele. Ale widzę, że pan to szlachetny kapitan. Nigdy nie odmawiaj pomocy kobiecie, jeśli jej potrzebuje! Zwyczaje tu dzikie, to przecież nie Europa. Często nie ma komu stanąć w obronie kobiecego honoru, godności, a czasem nawet życia...",
"Jeśli masz trochę smykałki i nie jesteś takim niezdarą jak mój mąż, to bez problemu samodzielnie zrobisz amunicję, złożysz skomplikowane urządzenie, uwarzysz miksturę, a nawet stworzysz amulet o magicznych właściwościach. Wystarczy mieć odpowiednie składniki, narzędzia i oczywiście przepisy.",
};

// Слухи матросов
string SAILOR_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Niełatwo znaleźć porządnego kapitana, co? Takiego, co zadba o załogę i wypłaci żołd na czas. Kupiec patrzy tylko na własną kieszeń, żeby grosza nie stracić, a dla wojskowych jesteśmy tylko mięsem armatnim. A przecież to na nas cały okręt się trzyma. Dbajcie o swoich marynarzy, kapitanie – my też ludzie!",
"Wczoraj nasz kapitan zamówił dla całej załogi dziewczyny z burdelu... Ale była zabawa! Zawsze płaci żołd w całości i na czas. Na morzu codziennie wieczorem daje nam pintę porządnego rumu, a kto wraca z nocnej wachty – temu nawet dwie. Za naszego kapitana gardło każdemu byśmy przegryźli! Takiego to ze świecą szukać!",
"Nasz kapitan wiecznie zatrudnia tych żabojadów. A oni nawet nie wiedzą, z której strony podejść do olinowania. Francuzom do angielskich marynarzy jeszcze daleko... Chociaż trzeba przyznać, artylerzystów mają świetnych – pewnie od małego przy armatach siedzą. Ale najważniejsze na statku to przecież żagle, prawda, kapitanie?",
"Wiecie, kapitanie, jak mnie wkurzają te świeżaki na pokładzie! Nawet sobie nie wyobrażacie! Jednego czy dwóch jeszcze można znieść, ale jak na jednego doświadczonego marynarza przypada dziesięciu takich gamoni? Moim zdaniem lepiej mieć mniej załogi, ale żeby każdy znał się na robocie. A jakbyście nawet setkę szczurów lądowych na lugier wsadzili – i tak nic z tego nie będzie.",
"Powiem wam jedno – gorszych marynarzy niż w hiszpańskich koloniach to ze świecą szukać. Zanim nauczą się obsługiwać olinowanie, minie niejedna miesiąc. Ale za to w walce wręcz z szablą są prawdziwymi mistrzami, tego im nie można odmówić! Jeśli więc szykuje się ostra bitwa, Hiszpanie to świetny wybór – odważni z nich chłopcy!",
"Słyszeliście, co się ostatnio wydarzyło u wybrzeży tej wyspy? Na jednym z kupieckich statków wybuchł bunt – załoga wyrzuciła kapitana za burtę i popłynęła w nieznanym kierunku. I dobrze, bo ten kapitan był strasznym skąpcem, ludziom żałował pieniędzy i racje żywnościowe ucinał do granic przyzwoitości. Niech to będzie nauczka dla tych, co chcą się wzbogacić kosztem marynarzy.",
"Najlepszy kapitan to taki, który zawsze wypłaca załodze żołd na czas, nie pozwala marynarzom głodować ani chorować, dba o morale rumem i nie zapomina o rozrywkach dla swojej ekipy. A ty, kapitanie, możesz o sobie tak powiedzieć?",
"Kapitan, który nie docenia swojej załogi, długo kapitanem nie będzie. Nowicjusze z tawerny nie zrobią nawet ułamka tego, co potrafi zgrana i doświadczona ekipa. Dbaj o swoich ludzi, kapitanie – nie wystawiaj ich na ogień kartaczy, nie pchaj się do abordażu, jeśli nie masz pewności zwycięstwa. Czasem lepiej uciec bez chwały, niż zginąć z honorem.",
"Nie wiem, jak inni, ale ja nigdy nie zaciągnę się do kapitana, o którym mówią, że jest skąpy. Zanim się najmiemy, zawsze wypytujemy znajomych i karczmarza, co to za człowiek ten nasz przyszły szef. Pracować dla sknery – gorzej być nie może. Sam raz takiego miałem – cały czas musiałem chodzić w podartych portkach.",
"Powiem ci tak, kapitanie: jeśli twój marynarz jest najedzony, zdrowy, dobrze ubrany i obuty, ma trochę monet w kieszeni, a na lądzie zawsze czeka na niego rum i kobiece wdzięki – to za ciebie każdego pirata rozerwie na strzępy i będzie ci wierny do ostatniego tchu. Liny zawsze będą w porządku, działa wyczyszczone, a proch suchy. Pamiętaj o tym! Dbaj o morale swojej załogi!",
};

// Если новостей нет в LSC
string NO_RUMOUR_LSC_TEXT[5] = {
"Nudno u nas na wyspie. O jakich nowościach mówicie?..",
"Jakie plotki? Dopóki narwale i rivaidos znów się nie pokłócą, będzie tu spokojnie.",
"Nic ciekawego się nie dzieje... Ciekawie zrobi się dopiero wtedy, gdy skończą się zapasy żywności.",
"Nic nowego... Dopóki piraci nie skopią tyłków jakiemuś klanowi albo klany same się nie pozagryzają.",
"Żadnych nowin, żadnych plotek. Przynajmniej dopóki znowu nie wybuchnie bójka między klanami.",
};
